;;2015-08-28
;; PCSYMS ====================================
*csq-data-list =
(:PCSYM-ELM-LISTS ((A4 (MOTHER FATHER BEST-M-FRIEND (A4 "a vs nota" :SINGLE "Extremely important" "0.833" 10 1 12 10 SCORED-NORMAL PRIORITY12))) (B7 (MOTHER FATHER BEST-F-FRIEND (B7 "b vs notb" :SINGLE "Extremely important" "0.833" 10 1 12 10 SCORED-NORMAL PRIORITY12))) (C0 (MOTHER BEST-M-FRIEND BEST-F-FRIEND (C0 "c vs notc" :SINGLE "Extremely important" "0.833" 10 1 12 10 SCORED-NORMAL PRIORITY12))) (D4 (FATHER BEST-M-FRIEND BEST-F-FRIEND (D4 "d vs NOTD" :SINGLE "Extremely important" "0.833" 10 1 12 10 SCORED-NORMAL PRIORITY12)))) :PC-VALUES)

CL-USER 12 > A4
("A4" "a vs nota" CS2-1-1-99 NIL NIL :PC ("a" "nota" 1 NIL) :POLE1 "a" :POLE2 "nota" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL FATHER NIL) (POLE1 NIL BEST-M-FRIEND NIL) (POLE2 NIL MOTHER NIL))))

CL-USER 13 > B7
("B7" "b vs notb" CS2-1-1-99 NIL NIL :PC ("b" "notb" 1 NIL) :POLE1 "b" :POLE2 "notb" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL FATHER NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL MOTHER NIL))))

CL-USER 14 > C0
("C0" "c vs notc" CS2-1-1-99 NIL NIL :PC ("c" "notc" 1 NIL) :POLE1 "c" :POLE2 "notc" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL BEST-M-FRIEND NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL MOTHER NIL))))

CL-USER 15 > D4
("D4" "d vs NOTD" CS2-1-1-99 NIL NIL :PC ("d" "NOTD" 1 NIL) :POLE1 "d" :POLE2 "NOTD" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL BEST-M-FRIEND NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL FATHER NIL))))


;;ELMSYMS ========================
(:ELMSYM-LISTS (MOTHER ("MOTHER" "mother" ELM2-1-1-99 NIL NIL) ("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL "dave") ("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL "jan")) (FATHER ("FATHER" "father" ELM3-1-1-99 NIL NIL)) (BEST-M-FRIEND ("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL NIL)) (BEST-F-FRIEND ("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL NIL)))

CL-USER 7 > mother
("MOTHER" "mother" ELM2-1-1-99 NIL NIL :BIPATHS (((MOTHER NIL (A4 (POLE2) NIL))) ((MOTHER NIL (B7 (POLE2) NIL))) ((MOTHER NIL (C0 (POLE2) NIL)))))

CL-USER 8 > father
("FATHER" "father" ELM3-1-1-99 NIL NIL :BIPATHS (((FATHER NIL (A4 (POLE1) NIL))) ((FATHER NIL (B7 (POLE1) NIL))) ((FATHER NIL (D4 (POLE2) NIL)))))

CL-USER 9 > best-m-friend
("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL "dave" :BIPATHS (((BEST-M-FRIEND NIL (A4 (POLE1) NIL))) ((BEST-M-FRIEND NIL (C0 (POLE1) NIL))) ((BEST-M-FRIEND NIL (D4 (POLE1) NIL)))))

CL-USER 10 > best-f-friend
("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL "jan" :BIPATHS (((BEST-F-FRIEND NIL (B7 (POLE1) NIL))) ((BEST-F-FRIEND NIL (C0 (POLE1) NIL))) ((BEST-F-FRIEND NIL (D4 (POLE1) NIL)))))
















;;2016-08-7

;; --------------------------------------------- ELMSYM DATA ---------------------------------------
CL-USER 64 > *csq-elmsym-lists
(:ELMSYM-LISTS (("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL "dave") ("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL "jan")))
;;(setf *csq-elmsym-lists '(:ELMSYM-LISTS (("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL "dave") ("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL "jan"))))

CL-USER 2 > mother
("MOTHER" "mother" ELM2-1-1-99 NIL NIL :BIPATHS (((MOTHER NIL (A2 (POLE2) NIL))) ((MOTHER NIL (B3 (POLE1) NIL))) ((MOTHER NIL (C5 (POLE1) NIL)))))
CL-USER 3 > father
("FATHER" "father" ELM3-1-1-99 NIL NIL :BIPATHS (((FATHER NIL (A2 (POLE1) NIL))) ((FATHER NIL (B3 (POLE2) NIL))) ((FATHER NIL (D2 (POLE2) NIL)))))
CL-USER 65 > best-m-friend
("BEST-M-FRIEND" "best-m-friend" ELM4-1-1-99 NIL "dave" :BIPATHS (((BEST-M-FRIEND NIL (A3 (POLE1) NIL))) ((BEST-M-FRIEND NIL (C5 (POLE1) NIL))) ((BEST-M-FRIEND NIL (D1 (POLE1) NIL)))))
CL-USER 4 > best-f-friend
("BEST-F-FRIEND" "best-f-friend" ELM5-1-1-99 NIL "jan" :BIPATHS (((BEST-F-FRIEND NIL (B3 (POLE1) NIL))) ((BEST-F-FRIEND NIL (C5 (POLE2) NIL))) ((BEST-F-FRIEND NIL (D2 (POLE1) NIL)))))

;;--------------------------------------------- PC DATA --------------------------------------
CL-USER 66 > *csq-data-list
(:PCSYM-ELM-LISTS ((A3 (MOTHER FATHER BEST-M-FRIEND)) (B3 (MOTHER FATHER BEST-F-FRIEND)) (C5 (MOTHER BEST-M-FRIEND BEST-F-FRIEND)) (D1 (FATHER BEST-M-FRIEND BEST-F-FRIEND))) :PC-VALUES ((A3 "a vs not a" :SINGLE "One of the most important things in my life" "0.917" 11 1 12 11 SCORED-NORMAL PRIORITY12) (B3 "b vs not b" :SINGLE "One of the most negative things/fears in my life" "0.167" 2 1 12 2 SCORED-NORMAL PRIORITY12) (C5 "c vs not c" :SINGLE "Mildly important" "0.583" 7 1 12 7 SCORED-NORMAL PRIORITY12) (D1 "d vs not d" :SINGLE "The most important (positive) thing in my life" "1.000" 12 1 12 12 SCORED-NORMAL PRIORITY12)))

CL-USER 67 > a3
("A3" "a vs not a" CS2-1-1-99 NIL NIL :PC ("a" "not a" 1 NIL) :POLE1 "a" :POLE2 "not a" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL FATHER NIL) (POLE1 NIL BEST-M-FRIEND NIL) (POLE2 NIL MOTHER NIL))))
CL-USER 6 > b3
("B3" "b vs not b" CS2-1-1-99 NIL NIL :PC ("b" "not b" 1 NIL) :POLE1 "b" :POLE2 "not b" :BESTPOLE 1 (:BIPATHS ((POLE1 NIL MOTHER NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL FATHER NIL) ((POLE1 NIL MOTHER NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL FATHER NIL)))))
CL-USER 7 > c5
("C5" "c vs not c" CS2-1-1-99 NIL NIL :PC ("c" "not c" 2 NIL) :POLE1 "c" :POLE2 "not c" :BESTPOLE 2 (:BIPATHS ((POLE1 NIL BEST-M-FRIEND NIL) (POLE1 NIL BEST-F-FRIEND NIL) (POLE2 NIL MOTHER NIL) ((POLE1 NIL MOTHER NIL) (POLE1 NIL BEST-M-FRIEND NIL) (POLE2 NIL BEST-F-FRIEND NIL)))))
CL-USER 8 > d1
("D1" "d vs not d" CS2-1-1-99 NIL NIL :PC ("d" "not d" 0 NIL) :POLE1 "d" :POLE2 "not d" :BESTPOLE 0 (:BIPATHS ((POLE1 NIL FATHER NIL) (POLE1 NIL BEST-M-FRIEND NIL) (POLE2 NIL BEST-F-FRIEND NIL))))

DIAGRAM OF ABOVE ==============================

   A--NOT A             B--NOT B           C--NOT C               D--NOT D (val= 1.0 best-pole 0)
                                                                                               |          |
                                |-----------------------------------------------|          |                                                                            |                           |--------------------------|          |
                                |                           |                                             |
  MOTHER        FATHER     BEST-M-FRIEND    BEST-F-FRIEND



;;XXX  END OF NEW TEST DATA -----------------------------------------------















;;add (setf *CSQ-elmsym-lists
 :CSQ-ELMDATA-LIST
 '(((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Dave D") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Jan B") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Donald T") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Dragon Lady") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Dr Stowe") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("E Warren") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Tom B") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Sherry") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Staats") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Jerry") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Mike F") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Bob K") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Cary G") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("FDR") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Cobb") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("Jesus") NIL NIL NIL))
  ((NIL :SINGLE-TEXT NIL NIL 1 NIL ("5th Grade") NIL NIL NIL))
  ;;add )))
  ;;add (setf *csq-data-list  '(:PCSYM-ELM-LISTS (
  (DEEPTHINKER (MOTHER ROLE-MODEL CHILD-FRIEND))
  (KIND (BEST-F-FRIEND M-DISLIKE CHILD-FRIEND))
  (HONEST (M-DISLIKE F-ADMIRE FAV-BOSS))
  (CARERE-MANY (BEST-M-FRIEND M-ADMIRE WORST-BOSS))
  (INCONSIDERATE (FATHER ROLE-MODEL CHILD-DISLIKE))
  (CONTEMPTABLE (F-DISLIKE WORK-PER-DISLIKE FAV-SPIRITUAL))
  (LOWIMPACT (WORST-BOSS FAV-POLITICO DIS-TEACHER))
  (CRUDE (M-ADMIRE CHILD-DISLIKE WORK-PER-DISLIKE))
  (BRILLIANTWORLDVIEW (FAV-BOSS FAV-POLITICO FAV-TEACHER))
  (HUMOR (FAV-BOSS FAV-M-STAR DIS-TEACHER))
  (UNDERSTANDING (MOTHER WORST-BOSS FAV-M-STAR))
  (ADVEDUCATION (MOTHER M-ADMIRE ROLE-MODEL))
  (NOTIMPULSIVE (CHILD-DISLIKE WORK-PER-DISLIKE FAV-BOSS))
  (INTELLECTUAL (BEST-M-FRIEND FAV-BOSS FAV-TEACHER))
  (PSYCHOLOGISTS (BEST-M-FRIEND PER-MOSTFUN WORK-FRIEND))
  (INTIMATE (BEST-F-FRIEND F-ADMIRE FAV-POLITICO))
  (DISTINQUISHED (ROLE-MODEL FAV-M-STAR DIS-TEACHER))
  (LOYAL (PER-ROMANCE CHILD-FRIEND DIS-TEACHER))
  (BRILLIANT (BEST-M-FRIEND BEST-F-FRIEND ROLE-MODEL))
  (NOT (MOTHER FATHER WORST-BOSS))
  (STORYTELLER (MOTHER PER-MOSTFUN FAV-POLITICO))
  (SOCIALCONCERN (BEST-M-FRIEND BEST-F-FRIEND F-ADMIRE))
  (SPIRITUAL (WORK-PER-DISLIKE FAV-TEACHER FAV-SPIRITUAL))
  (BOISTEROUS (PER-MOSTFUN CHILD-FRIEND FAV-TEACHER))
  (HUMBLE (BEST-F-FRIEND ROLE-MODEL CHILD-FRIEND))
  (DIRECT (PER-ROMANCE WORK-FRIEND WORK-PER-DISLIKE))
  (CLASSY (M-ADMIRE PER-ROMANCE CHILD-DISLIKE))
  (LEARNING-THEORISTS (ROLE-MODEL WORK-FRIEND FAV-BOSS))
  (MENTOR (MOTHER PER-MOSTFUN ROLE-MODEL))
  (FAMILY-ORIENTED (PER-ROMANCE WORK-FRIEND DIS-TEACHER))
  (EMPATHETIC (M-ADMIRE PER-ROMANCE WORK-PER-DISLIKE))
  (PHYSATTRACTIVE (PER-ROMANCE ROLE-MODEL FAV-POLITICO))
  (NOT1 (F-ADMIRE WORST-BOSS DIS-TEACHER))
  (COLLABORATIVE (MOTHER CHILD-FRIEND WORK-FRIEND))
  (ROMANTIC (F-ADMIRE PER-MOSTFUN FAV-M-STAR))
  (HIGHTEMPER (FATHER PER-ROMANCE WORK-FRIEND))
  (AMBITIOUS (FATHER FAV-POLITICO DIS-TEACHER))
  (SOCIAL-FOCUSED (BEST-M-FRIEND CHILD-FRIEND FAV-M-STAR))
  (NOT7 (BEST-M-FRIEND CHILD-DISLIKE WORST-BOSS))
  (KNOWLEDGESPECIALIS (ROLE-MODEL WORK-FRIEND DIS-TEACHER))
  (NOTMANIPULATIVE (M-DISLIKE PER-ROMANCE FAV-TEACHER))
  (CURIOUS (CHILD-FRIEND WORST-BOSS FAV-TEACHER))
  (CHANGEDAREA (M-ADMIRE F-ADMIRE FAV-SPIRITUAL))
  (NOTATHELETIC (CHILD-FRIEND WORST-BOSS DIS-TEACHER))
  (DISORGANIZED (F-DISLIKE FAV-BOSS FAV-POLITICO))
  (NOTSACRIFICED (BEST-M-FRIEND WORK-PER-DISLIKE FAV-SPIRITUAL))
  (INFORMAL (BEST-F-FRIEND M-ADMIRE CHILD-FRIEND))
  (NOTANALYTIC (CHILD-DISLIKE WORST-BOSS FAV-TEACHER))
  (NOT0 (ROLE-MODEL WORK-PER-DISLIKE FAV-POLITICO))
  (INSIGHTFUL (MOTHER ROLE-MODEL CHILD-DISLIKE))
  (OPEN (F-DISLIKE ROLE-MODEL CHILD-FRIEND))
  (DEMOCRATIC-EQUALIT (FATHER BEST-M-FRIEND FAV-TEACHER))
  (ATTENTION-SEEKER (M-DISLIKE ROLE-MODEL FAV-M-STAR))
  (COUNSELOR (M-ADMIRE PER-MOSTFUN PER-ROMANCE))
  (PUTOTHERSFIRST (MOTHER WORK-FRIEND FAV-SPIRITUAL))
  (PREACHERS (BEST-M-FRIEND M-ADMIRE PER-ROMANCE))
  (SEXY (PER-ROMANCE CHILD-DISLIKE FAV-BOSS))
  (END-JUSTIFY-MEANS (FATHER M-DISLIKE WORK-PER-DISLIKE))
  (PARTYER (BEST-F-FRIEND CHILD-DISLIKE FAV-SPIRITUAL))
  (FOLLOWRULES (MOTHER WORK-FRIEND WORK-PER-DISLIKE))
  (OKIES (M-ADMIRE F-ADMIRE WORK-FRIEND))
  (POLITICALIMACT (F-ADMIRE FAV-M-STAR FAV-POLITICO))
  (DOMINEERING (M-DISLIKE PER-MOSTFUN DIS-TEACHER))
  (RESPECTED (BEST-M-FRIEND M-DISLIKE FAV-POLITICO))
  (SOCIAL-ATTRACTION (PER-ROMANCE FAV-SPIRITUAL DIS-TEACHER))
  (BOYISHCHARM (F-ADMIRE FAV-M-STAR FAV-TEACHER))
  (LAUGHLOTS (BEST-M-FRIEND BEST-F-FRIEND PER-ROMANCE))
  (EVIL (F-DISLIKE ROLE-MODEL FAV-BOSS))
  (PEACEFUL (WORST-BOSS FAV-POLITICO FAV-SPIRITUAL))
  (DISTINGUISHEDLOOKI (FATHER BEST-F-FRIEND ROLE-MODEL))
  (CRUDE6 (CHILD-DISLIKE FAV-TEACHER DIS-TEACHER))
  (SALES-ORIENTED (FATHER M-DISLIKE PER-ROMANCE))
  (POLITICALASSERTIVE (M-DISLIKE F-ADMIRE WORST-BOSS))
  (THOUGHTFUL (MOTHER CHILD-DISLIKE FAV-POLITICO))
  (FUN-LOVING (F-DISLIKE PER-MOSTFUN FAV-M-STAR))
  (SCHOLARLY (BEST-M-FRIEND PER-ROMANCE ROLE-MODEL))
  (AGGRESSIVE (FATHER PER-ROMANCE CHILD-DISLIKE))
  (EDUCATORS (BEST-M-FRIEND PER-MOSTFUN PER-ROMANCE))
  (NOT8 (PER-ROMANCE ROLE-MODEL FAV-BOSS))
  (GOSPEL-PREACHER (M-ADMIRE PER-ROMANCE FAV-SPIRITUAL))
  (NOT0 (FAV-BOSS FAV-SPIRITUAL DIS-TEACHER))
  (VINDICTIVE (BEST-M-FRIEND F-DISLIKE DIS-TEACHER))
  (MUSIC-LOVER (BEST-F-FRIEND M-ADMIRE WORK-PER-DISLIKE))
  (DISTRUCTIVE (MOTHER M-DISLIKE F-DISLIKE))
  (NWC (F-ADMIRE CHILD-FRIEND WORST-BOSS))
  (LOVESWOMEN (PER-MOSTFUN WORK-PER-DISLIKE FAV-M-STAR))
  (HELPMINORITIES (BEST-M-FRIEND FAV-TEACHER DIS-TEACHER))
  (MECHANICAL (F-ADMIRE PER-MOSTFUN FAV-BOSS))
  (HELPPOOR (F-ADMIRE CHILD-FRIEND FAV-SPIRITUAL))
  (SUPPORTIVE (FATHER BEST-F-FRIEND FAV-BOSS))
  (LOVESTENNIS (BEST-M-FRIEND FAV-BOSS DIS-TEACHER))
  (LISTENER (FATHER PER-ROMANCE CHILD-FRIEND))
  (SELF-DEVELOPMENT (M-ADMIRE PER-ROMANCE DIS-TEACHER))
  (FLAMBOYANT (M-DISLIKE F-ADMIRE FAV-M-STAR))
  (OUTRAGEOUS (BEST-F-FRIEND M-DISLIKE ROLE-MODEL))
  (CREATIVE (ROLE-MODEL FAV-POLITICO DIS-TEACHER))
  (MARRIAGE-PRIORITY (BEST-F-FRIEND PER-MOSTFUN FAV-M-STAR))
  (NASTY (M-DISLIKE CHILD-DISLIKE FAV-TEACHER))
  (WEAKERCHAR (WORK-FRIEND FAV-M-STAR FAV-SPIRITUAL))
  (DETERMINED (F-ADMIRE CHILD-FRIEND FAV-TEACHER))
  (ORDINARY (BEST-M-FRIEND FAV-BOSS FAV-SPIRITUAL))
  (LOVING (M-DISLIKE M-ADMIRE PER-ROMANCE))
  (HOME-BODY (PER-ROMANCE CHILD-FRIEND FAV-POLITICO))
  (CAREFORUNDERDOG (M-ADMIRE ROLE-MODEL FAV-POLITICO))
  (PERFECTIONISTIC (MOTHER M-DISLIKE FAV-BOSS))
  (COOPERATIVE (CHILD-FRIEND FAV-BOSS WORST-BOSS))
  (TEAMPLAYER (M-DISLIKE PER-MOSTFUN WORK-PER-DISLIKE))
  (GLOBALPERSPECTIVE (WORK-FRIEND FAV-POLITICO FAV-SPIRITUAL))
  (SELF-CONTROL (WORK-PER-DISLIKE FAV-M-STAR FAV-TEACHER))
  (THEORETICIAN (MOTHER ROLE-MODEL FAV-BOSS))
  (TENNISPLAYERS (BEST-M-FRIEND PER-ROMANCE WORK-FRIEND))
  (CONVENTIONAL (MOTHER WORK-FRIEND FAV-POLITICO))
  (MATHEMATICAL (BEST-M-FRIEND WORK-PER-DISLIKE FAV-M-STAR))
  (FLIRTATIOUS (PER-ROMANCE CHILD-DISLIKE WORST-BOSS))
  (CUNNING (FATHER M-DISLIKE CHILD-FRIEND))
  (METHODEXPERT (WORK-FRIEND WORK-PER-DISLIKE FAV-M-STAR))
  (CHILDFRIENDS (ROLE-MODEL CHILD-FRIEND DIS-TEACHER))
  (GENUINE (M-DISLIKE PER-ROMANCE FAV-POLITICO))
  (BUSINESSMAN (FATHER WORK-PER-DISLIKE FAV-BOSS))
  (LIBERAL (BEST-M-FRIEND F-ADMIRE FAV-M-STAR))
  (WIN-WIN (BEST-M-FRIEND F-DISLIKE PER-MOSTFUN))
  (UNDERSTANDPOVERTY (FATHER WORK-PER-DISLIKE FAV-POLITICO))
  (SELF-MANAGEMENT (CHILD-DISLIKE WORK-FRIEND FAV-POLITICO))
  (PARENTS (MOTHER FATHER M-DISLIKE))
  (SARCASTIC (M-DISLIKE CHILD-DISLIKE DIS-TEACHER))
  (PHILOSOPHIC (FAV-M-STAR FAV-POLITICO FAV-TEACHER))
  (THRIFTY (F-ADMIRE WORK-FRIEND WORST-BOSS))
  (FAIR (BEST-M-FRIEND F-DISLIKE F-ADMIRE))
  (ROLEMODEL (M-ADMIRE FAV-BOSS FAV-SPIRITUAL))
  (CLOSEFRIEND (BEST-M-FRIEND ROLE-MODEL CHILD-FRIEND))
  (SOFT-SPOCKEN (FATHER FAV-BOSS FAV-TEACHER))
  (FLEXIBLE (F-DISLIKE PER-ROMANCE FAV-SPIRITUAL)))
 ;;add ))

;;MAKE FUNCTION TO GENERATE FOLLOWING FROM ABOVE
;; gen info is the info that the PC was set to.
;; (setf *CSQ-PCXDATA-LIST   (DEEPTHINKER (gen info here ))      (KIND (gen info here )) )    (HONEST (gen info here )) ) ;;etc


 NIL
 NIL
 "ERROR: NO TEXT, QUESTION MAY NOT BE:SINGLE TEXT TYPE"
 NIL
 NIL
 "ERROR: NO TEXT, QUESTION MAY NOT BE:SINGLE TEXT TYPE"
 NIL
 NIL
 "ERROR: NO TEXT, QUESTION MAY NOT BE:SINGLE TEXT TYPE")


SSSS START FIX THIS BUG The slot CAPI::INITIAL-TEXT is missing from #<CAPI:RICH-TEXT-PANE
