;;(pprint *file-all-pcqvar-lists)
(setf  *file-all-pcqvar-lists
 '(("A"
  "A vs NA"
  NIL
  "A"
  ("A" "1" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("B"
  "B vs NB"
  NIL
  "B"
  ("B" "2" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("C"
  "C vs NC"
  NIL
  "C"
  ("C" "3" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CAREFOROTHERS"
  "CARE FOR OTHERS vs SELFISH"
  NIL
  "CAREFOROTHERS"
  ("CAREFOROTHERS" "1" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INTIMATE"
  "INTIMATE vs NOT INTIMATE"
  NIL
  "INTIMATE"
  ("INTIMATE" "2" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("FLEXIBLE"
  "FLEXIBLE vs RIGID"
  NIL
  "FLEXIBLE"
  ("FLEXIBLE" "3" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CASUAL"
  "CASUAL vs FORMAL"
  NIL
  "CASUAL"
  ("CASUAL" "4" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("EGOTISTICAL"
  "EGOTISTICAL vs HUMBLE"
  NIL
  "EGOTISTICAL"
  ("EGOTISTICAL" "5" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("EXUBERANT"
  "EXUBERANT vs INHIBITED"
  NIL
  "EXUBERANT"
  ("EXUBERANT" "6" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("NOTTHEORIST"
  "NOT THEORIST vs ACCOMPLISHED THEORIST"
  NIL
  "NOTTHEORIST"
  ("NOTTHEORIST" "7" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LOVEX"
  "LOVE ME vs INDIFFERENT"
  NIL
  "LOVEX"
  ("LOVEX" "8" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LOVEDANCE"
  "LOVE DANCE vs NOT LOVE DANCE"
  NIL
  "LOVEDANCE"
  ("LOVEDANCE" "9" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HELPINGCAREER"
  "HELPING CAREER vs NOT HELPING CAREER"
  NIL
  "HELPINGCAREER"
  ("HELPINGCAREER" "10" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HIGHIMPACT"
  "HIGH IMPACT vs LO IMPACT"
  NIL
  "HIGHIMPACT"
  ("HIGHIMPACT" "11" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PSYCHOLOGISTS"
  "PSYCHOLOGISTS vs NOT PSYCH"
  NIL
  "PSYCHOLOGISTS"
  ("PSYCHOLOGISTS" "12" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("UNDERSTANDING"
  "UNDERSTANDING vs NOT UNDERSTANDING"
  NIL
  "UNDERSTANDING"
  ("UNDERSTANDING" "13" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("IMPULSIVE"
  "IMPULSIVE vs NOT IMPULSIVE"
  NIL
  "IMPULSIVE"
  ("IMPULSIVE" "14" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ENTERTAINER"
  "ENTERTAINER vs NOT ENTERTAINER"
  NIL
  "ENTERTAINER"
  ("ENTERTAINER" "15" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("AGGRESSIVE"
  "AGGRESSIVE vs CALM-ASSERTIVE"
  NIL
  "AGGRESSIVE"
  ("AGGRESSIVE" "16" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PATERNAL"
  "PATERNAL vs NOT PATERNAL"
  NIL
  "PATERNAL"
  ("PATERNAL" "17" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CAREABOUTOTHERSFEE"
  "CARE ABOUT OTHERS FEELINGS vs NOT CARE"
  NIL
  "CAREABOUTOTHERSFEE"
  ("CAREABOUTOTHERSFEE" "18" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INSPIREOTHERS"
  "INSPIRE OTHERS vs NOT INSPIRE"
  NIL
  "INSPIREOTHERS"
  ("INSPIREOTHERS" "19" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("BESTFRIEND"
  "BEST FRIEND vs ENEMY"
  NIL
  "BESTFRIEND"
  ("BESTFRIEND" "20" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DIRECT-HONEST"
  "DIRECT-HONEST vs SNEAKY-GAMES"
  NIL
  "DIRECT-HONEST"
  ("DIRECT-HONEST" "21" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("UNBRIDLEDHUMOR"
  "UNBRIDLED HUMOR vs PC-KIND-HUMOR"
  NIL
  "UNBRIDLEDHUMOR"
  ("UNBRIDLEDHUMOR" "22" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("FANTASYWORLD"
  "FANTASY WORLD vs REALISTIC"
  NIL
  "FANTASYWORLD"
  ("FANTASYWORLD" "23" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ATHLETIC"
  "ATHLETIC vs NOT ATHELTIC"
  NIL
  "ATHLETIC"
  ("ATHLETIC" "24" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ESPOSECHRISTIAN"
  "ESPOSE CHRISTIAN vs NOT ESPOUSE CHRISTIAN"
  NIL
  "ESPOSECHRISTIAN"
  ("ESPOSECHRISTIAN" "25" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CRITICAL"
  "CRITICAL vs NOT CRITICAL"
  NIL
  "CRITICAL"
  ("CRITICAL" "26" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SEXDEVIANCE"
  "SEX  DEVIANCE vs NOT SEX DEVIANCE"
  NIL
  "SEXDEVIANCE"
  ("SEXDEVIANCE" "27" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GLOBALPERSPECTIVE"
  "GLOBAL PERSPECTIVE vs NARROW PERSPECTIVE"
  NIL
  "GLOBALPERSPECTIVE"
  ("GLOBALPERSPECTIVE" "28" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("FUNCOMPANION"
  "FUN COMPANION vs NOT FUN COMPAN"
  NIL
  "FUNCOMPANION"
  ("FUNCOMPANION" "29" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SELF-DISCLOSE"
  "SELF-DISCLOSE vs NOT SELF-DISCLOSE"
  NIL
  "SELF-DISCLOSE"
  ("SELF-DISCLOSE" "30" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("MISSIONSPREADPSYCH"
  "MISSION TO SPREAD PSYCH KNOWLEDGE vs NOT PSY MISSION"
  NIL
  "MISSIONSPREADPSYCH"
  ("MISSIONSPREADPSYCH" "31" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CRUEL"
  "CRUEL vs NOT CRUEL"
  NIL
  "CRUEL"
  ("CRUEL" "32" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("COURTEOUS"
  "COURTEOUS vs NOT COURTEOUS"
  NIL
  "COURTEOUS"
  ("COURTEOUS" "33" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DEEPUNDERSTANDPEOP"
  "DEEP UNDERSTAND PEOPLE vs NOT DEEP UNDERSTAND PEOPLE"
  NIL
  "DEEPUNDERSTANDPEOP"
  ("DEEPUNDERSTANDPEOP" "34" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DEMOCRATICLEADER"
  "DEMOCRATIC LEADER vs AUTOCRATIC"
  NIL
  "DEMOCRATICLEADER"
  ("DEMOCRATICLEADER" "35" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PSYCHOLOGIST"
  "PSYCHOLOGIST vs NOT PSYCH"
  NIL
  "PSYCHOLOGIST"
  ("PSYCHOLOGIST" "36" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("METICULOUS"
  "METICULOUS vs NOT METICULOUS"
  NIL
  "METICULOUS"
  ("METICULOUS" "37" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("COGNITIVEPSYCHS"
  "COGNITIVE  PSYCHS vs NOT COG PSY"
  NIL
  "COGNITIVEPSYCHS"
  ("COGNITIVEPSYCHS" "38" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("EMOTIONAL"
  "EMOTIONAL vs NOT EMOTIONAL"
  NIL
  "EMOTIONAL"
  ("EMOTIONAL" "39" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CHARMING"
  "CHARMING vs NOT CHARMING"
  NIL
  "CHARMING"
  ("CHARMING" "40" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("VALUEGROUPHAPPINES"
  "HI VALUE GROUP HAPPINESS vs LO VAL GROUP HAPPY"
  NIL
  "VALUEGROUPHAPPINES"
  ("VALUEGROUPHAPPINES" "41" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LOCALLEADER"
  "LOCAL LEADER vs GLOBAL LEADER"
  NIL
  "LOCALLEADER"
  ("LOCALLEADER" "42" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HIGHLYEDUCATED"
  "HIGHLY EDUCATED vs LESS EDUCATION"
  NIL
  "HIGHLYEDUCATED"
  ("HIGHLYEDUCATED" "43" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ENLIGHTENWORLD"
  "ENLIGHTEN WORLD vs NOT ENLIGHTEN WORLD"
  NIL
  "ENLIGHTENWORLD"
  ("ENLIGHTENWORLD" "44" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PETTY"
  "PETTY vs BIG ISSUE FOCUS"
  NIL
  "PETTY"
  ("PETTY" "45" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ENCOURAGING"
  "ENCOURAGING vs DISCOURAGING"
  NIL
  "ENCOURAGING"
  ("ENCOURAGING" "46" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HUMOROUS"
  "HUMOROUS vs NOT HUMOROUS"
  NIL
  "HUMOROUS"
  ("HUMOROUS" "47" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GREATLEADER"
  "GREAT LEADER vs NOT GREAT LEADER"
  NIL
  "GREATLEADER"
  ("GREATLEADER" "48" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CONFIDENT-SELF-EST"
  "CONFIDENT-SELF-ESTEEM vs NOT CONFIDENT"
  NIL
  "CONFIDENT-SELF-EST"
  ("CONFIDENT-SELF-EST" "49" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INTERPERSONALSKILL"
  "INTERPERSONAL SKILLS vs NOT INTERP SKILLS"
  NIL
  "INTERPERSONALSKILL"
  ("INTERPERSONALSKILL" "50" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INTIMATELYASSERTIV"
  "INTIMATELY ASSERTIVE LEADER vs NOT INTIMATE-ASSERT"
  NIL
  "INTIMATELYASSERTIV"
  ("INTIMATELYASSERTIV" "51" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GREATSPEAKER"
  "GREAT SPEAKER vs NOT GREAT SPEAKER"
  NIL
  "GREATSPEAKER"
  ("GREATSPEAKER" "52" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("AUTONOMOUS"
  "AUTONOMOUS vs NOT AUTONOMOUS"
  NIL
  "AUTONOMOUS"
  ("AUTONOMOUS" "53" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HIGHINTELLIGENCE"
  "HIGH INTELLIGENCE vs NOT INTELLIGENT"
  NIL
  "HIGHINTELLIGENCE"
  ("HIGHINTELLIGENCE" "54" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GOODNEGOTIATOR"
  "GOOD NEGOTIATOR vs NOT GOOD NEGOTIATOR"
  NIL
  "GOODNEGOTIATOR"
  ("GOODNEGOTIATOR" "55" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PROGRESSIVE"
  "PROGRESSIVE vs NOT PROGRESSIVE"
  NIL
  "PROGRESSIVE"
  ("PROGRESSIVE" "56" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CLOSE"
  "CLOSE TO ME vs DISTANT"
  NIL
  "CLOSE"
  ("CLOSE" "57" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PLAYFUL"
  "PLAYFUL vs NOT PLAYFUL"
  NIL
  "PLAYFUL"
  ("PLAYFUL" "58" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("COUNSELORS"
  "COUNSELORS vs NOT COUNSELOR"
  NIL
  "COUNSELORS"
  ("COUNSELORS" "59" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INDUSTRIOUS"
  "INDUSTRIOUS vs LESS INDUSTRIOUS"
  NIL
  "INDUSTRIOUS"
  ("INDUSTRIOUS" "60" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SEXY"
  "SEXY vs NOT SEXY"
  NIL
  "SEXY"
  ("SEXY" "61" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("UNDERSTANDING4"
  "UNDERSTANDING vs NOT UNDERSTANDING"
  NIL
  "UNDERSTANDING4"
  ("UNDERSTANDING4" "62" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SOFTSPOKEN"
  "SOFT SPOKEN vs NOT SOFT SPOKEN"
  NIL
  "SOFTSPOKEN"
  ("SOFTSPOKEN" "63" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("TEAMMATE"
  "TEAMMATE vs NOT TEAMMATE"
  NIL
  "TEAMMATE"
  ("TEAMMATE" "64" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("BEHAVIORALPSYCH"
  "BEHAVIORAL PSYCH vs NOT BEH PSY"
  NIL
  "BEHAVIORALPSYCH"
  ("BEHAVIORALPSYCH" "65" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("OPTIMISTIC"
  "OPTIMISTIC vs NOT OPTIMISTIC"
  NIL
  "OPTIMISTIC"
  ("OPTIMISTIC" "66" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CHILDHOODFRIEND"
  "CHILDHOOD FRIEND vs NOT CHILDHOOD FRIEND"
  NIL
  "CHILDHOODFRIEND"
  ("CHILDHOODFRIEND" "67" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DEBONAIRE"
  "DEBONAIRE vs NOT DEBONAIRE"
  NIL
  "DEBONAIRE"
  ("DEBONAIRE" "68" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HIGHSTANDARDS"
  "HIGH STANDARDS vs LOW STANDARDS"
  NIL
  "HIGHSTANDARDS"
  ("HIGHSTANDARDS" "69" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("TEACHER1"
  "TEACHER vs NOT TEACHER"
  NIL
  "TEACHER1"
  ("TEACHER1" "70" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LIBERALCHRISTIAN"
  "LIBERAL CHRISTIAN vs NOT LIBERAL CHRIST"
  NIL
  "LIBERALCHRISTIAN"
  ("LIBERALCHRISTIAN" "71" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("EMPATHETICLISTENER"
  "EMPATHETIC LISTENER vs NOT EMPATHETIC"
  NIL
  "EMPATHETICLISTENER"
  ("EMPATHETICLISTENER" "72" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("OVERCOMEDIFFICULTI"
  "OVERCOME DIFFICULTIES vs LESS OVERCOME"
  NIL
  "OVERCOMEDIFFICULTI"
  ("OVERCOMEDIFFICULTI" "73" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("FIGHTILLNESS"
  "FIGHT  ILLNESS vs NOT FIGHT ILLNESS"
  NIL
  "FIGHTILLNESS"
  ("FIGHTILLNESS" "74" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PUBLICSERVANT"
  "PUBLIC SERVANT vs NOT PUBLIC SERVANT"
  NIL
  "PUBLICSERVANT"
  ("PUBLICSERVANT" "75" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SECULAR"
  "SECULAR vs RELIGIOUS"
  NIL
  "SECULAR"
  ("SECULAR" "76" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SEEKATTENTION"
  "SEEK ATTENTION vs LESS SEEK ATTENTION"
  NIL
  "SEEKATTENTION"
  ("SEEKATTENTION" "77" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HELPER"
  "HELPER vs NOT HELPER"
  NIL
  "HELPER"
  ("HELPER" "78" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SPREADKNOWLEDGE"
  "SPREAD KNOWLEDGE vs NOT SPREAD KNOW"
  NIL
  "SPREADKNOWLEDGE"
  ("SPREADKNOWLEDGE" "79" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LAWFUL"
  "LAWFUL vs LESS LAWFUL"
  NIL
  "LAWFUL"
  ("LAWFUL" "80" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("MANAGER0"
  "MANAGER vs NOT MANAGER"
  NIL
  "MANAGER0"
  ("MANAGER0" "81" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PRAGMATIC"
  "PRAGMATIC vs NOT PRAGMATIC"
  NIL
  "PRAGMATIC"
  ("PRAGMATIC" "82" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GROUPKNOWLEDGEWORK"
  "GROUP KNOWLEDGE WORKER vs NOT GROUP KNOWL WORK"
  NIL
  "GROUPKNOWLEDGEWORK"
  ("GROUPKNOWLEDGEWORK" "83" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("VERBALSKILLS"
  "HI VERBAL SKILLS vs LO VERBAL SKILLS"
  NIL
  "VERBALSKILLS"
  ("VERBALSKILLS" "84" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LESSCIVILIZED"
  "LESS CIVILIZED vs CIVILIZED"
  NIL
  "LESSCIVILIZED"
  ("LESSCIVILIZED" "85" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("REPRESENTGROUP"
  "REPRESENT GROUP vs NOT REPRESENT GROUP"
  NIL
  "REPRESENTGROUP"
  ("REPRESENTGROUP" "86" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PERFORMER"
  "PERFORMER vs NOT PERFORMER"
  NIL
  "PERFORMER"
  ("PERFORMER" "87" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SHOWBUSINESS"
  "SHOW BUSINESS vs NOT SHOW BUSINESS"
  NIL
  "SHOWBUSINESS"
  ("SHOWBUSINESS" "88" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SOLVEPROBLEMS"
  "SOLVE PROBLEMS vs LESS SOLVE PROBLEMS"
  NIL
  "SOLVEPROBLEMS"
  ("SOLVEPROBLEMS" "89" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("STARPERFORMER"
  "A STAR PERFORMER vs NOT STAR PERFORMER"
  NIL
  "STARPERFORMER"
  ("STARPERFORMER" "90" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LESSWEALTH"
  "LESS WEALTH vs WEALTHY"
  NIL
  "LESSWEALTH"
  ("LESSWEALTH" "91" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DEPENDGOV"
  "DEPEND ON GOV vs LESS DEPEND ON GOV"
  NIL
  "DEPENDGOV"
  ("DEPENDGOV" "92" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("IMMIGRANTS"
  "IMMIGRANTS vs LESS IMMIGRANTS"
  NIL
  "IMMIGRANTS"
  ("IMMIGRANTS" "93" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PROFIT-ORIENTED"
  "PROFIT-ORIENTED vs LESS PROFIT-ORIENTED"
  NIL
  "PROFIT-ORIENTED"
  ("PROFIT-ORIENTED" "94" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("OCCUPATION"
  "OCCUPATION vs NOT OCCUPATION"
  NIL
  "OCCUPATION"
  ("OCCUPATION" "95" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PHYSICALWELLBEING"
  "PHYSICAL WELLBEING vs SPIRITUAL WELLBEING"
  NIL
  "PHYSICALWELLBEING"
  ("PHYSICALWELLBEING" "96" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LEGALEXPERT"
  "LEGAL EXPERT vs NOT LEGAL EXPERT"
  NIL
  "LEGALEXPERT"
  ("LEGALEXPERT" "97" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SELF-DISCIPLINE"
  "SELF-DISCIPLINE vs LESS SELF-DISCIPLINE"
  NIL
  "SELF-DISCIPLINE"
  ("SELF-DISCIPLINE" "98" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("ENFORCERULES"
  "ENFORCE RULES vs NOT ENFORCE RULES"
  NIL
  "ENFORCERULES"
  ("ENFORCERULES" "99" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CREATENEWRULES"
  "CREATE NEW RULES vs NOT CREATE RULES"
  NIL
  "CREATENEWRULES"
  ("CREATENEWRULES" "100" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SOCIALCONSTRAINTS"
  "SOCIAL CONSTRAINTS vs FREE FROM SOCIAL CONTRANTS"
  NIL
  "SOCIALCONSTRAINTS"
  ("SOCIALCONSTRAINTS" "101" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("RESPECTED"
  "RESPECTED vs NOT RESPECTED"
  NIL
  "RESPECTED"
  ("RESPECTED" "102" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SEEKEXTERNALAPPROV"
  "SEEK EXTERNAL APPROVAL vs NOT SEEK EXT APPROVAL"
  NIL
  "SEEKEXTERNALAPPROV"
  ("SEEKEXTERNALAPPROV" "103" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CREATIVE"
  "CREATIVE vs NOT CREATIVE"
  NIL
  "CREATIVE"
  ("CREATIVE" "104" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("RITUALISTIC"
  "RITUALISTIC vs NOT RITUALISTIC"
  NIL
  "RITUALISTIC"
  ("RITUALISTIC" "105" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("LESSMORALISTIC"
  "LESS MORALISTIC vs MORALISTIC"
  NIL
  "LESSMORALISTIC"
  ("LESSMORALISTIC" "106" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PROFESSIONAL"
  "PROFESSIONAL vs NOT PROFESSIONAL"
  NIL
  "PROFESSIONAL"
  ("PROFESSIONAL" "107" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("DRAMATIC"
  "DRAMATIC vs LESS DRAMATIC"
  NIL
  "DRAMATIC"
  ("DRAMATIC" "108" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("EUROCENTRICVALUES"
  "EUROCENTRIC VALUES vs NOT EUROENTRIC"
  NIL
  "EUROCENTRICVALUES"
  ("EUROCENTRICVALUES" "109" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INDIVIDUALISTIC"
  "INDIVIDUALISTIC vs GROUP-CONTROLLED"
  NIL
  "INDIVIDUALISTIC"
  ("INDIVIDUALISTIC" "110" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("CATHOLIC"
  "CATHOLIC vs NOT CATHOLIC"
  NIL
  "CATHOLIC"
  ("CATHOLIC" "111" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PEOPLE-JOB"
  "PEOPLE-JOB vs OBJECT-JOB"
  NIL
  "PEOPLE-JOB"
  ("PEOPLE-JOB" "112" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("GREEDY"
  "GREEDY vs NOT GREEDY"
  NIL
  "GREEDY"
  ("GREEDY" "113" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("OWNER"
  "OWNER vs NOT OWNER"
  NIL
  "OWNER"
  ("OWNER" "114" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PERFORMANCE-ORIENT"
  "PERFORMANCE-ORIENTED vs NOT PERFORM-ORIENTED"
  NIL
  "PERFORMANCE-ORIENT"
  ("PERFORMANCE-ORIENT" "115" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("HIGHSTATUS"
  "HIGH STATUS vs LOW STATUS"
  NIL
  "HIGHSTATUS"
  ("HIGHSTATUS" "116" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("RATIONAL"
  "RATIONAL vs NOT RATIONAL"
  NIL
  "RATIONAL"
  ("RATIONAL" "117" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PRACTICAL"
  "PRACTICAL vs NOT PRACTICAL"
  NIL
  "PRACTICAL"
  ("PRACTICAL" "118" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("PERSUASIVE"
  "PERSUASIVE  vs LESS PERSUASIVE"
  NIL
  "PERSUASIVE"
  ("PERSUASIVE" "119" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("INFLUENCIAL"
  "INFLUENCIAL vs NOT INFLUENCIAL"
  NIL
  "INFLUENCIAL"
  ("INFLUENCIAL" "120" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("MANUALWORK"
  "MANUAL WORK vs NOT MANUAL WORK"
  NIL
  "MANUALWORK"
  ("MANUALWORK" "121" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("NOTHISTORY-ORIENTE"
  "NOT HISTORY-ORIENTED vs HISTORY-ORIENTED"
  NIL
  "NOTHISTORY-ORIENTE"
  ("NOTHISTORY-ORIENTE" "122" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("NOTANALYTIC"
  "NOT ANALYTIC vs ANALYTIC THINKING"
  NIL
  "NOTANALYTIC"
  ("NOTANALYTIC" "123" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("NOTLOYAL"
  "NOT LOYAL vs LOYAL"
  NIL
  "NOTLOYAL"
  ("NOTLOYAL" "124" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SPIRITUALINTEGRATI"
  "SPIRITUAL INTEGRATION vs NOT SPIRIT INTEGR"
  NIL
  "SPIRITUALINTEGRATI"
  ("SPIRITUALINTEGRATI" "125" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SEEKULTIMATETRUTH"
  "SEEK ULTIMATE TRUTH vs NOT SEEK ULTIMATES"
  NIL
  "SEEKULTIMATETRUTH"
  ("SEEKULTIMATETRUTH" "126" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("MATERIALISTIC"
  "MATERIALISTIC vs NOT MATERIALISTIC"
  NIL
  "MATERIALISTIC"
  ("MATERIALISTIC" "127" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL))
 ("SKILLEDMOVEMENTS"
  "SKILLED MOVEMENTS vs NOT SKILLED MOVEMENTS"
  NIL
  "SKILLEDMOVEMENTS"
  ("SKILLEDMOVEMENTS" "128" PCSYM-VALQ "int" "Priority12" NIL 12 NIL NIL)))
  )