;;(pprint *file-elmsymvals)
(setf  *file-elmsymvals
'(("MOTHER"
  "mother"
  ELM2-1-1-99
  NIL
  NIL
  :BIPATHS
  (((MOTHER NIL (CAREFOROTHERS (POLE1) NIL)))
   ((MOTHER NIL (INTIMATE (POLE1) NIL)))
   ((MOTHER NIL (FLEXIBLE (POLE1) NIL)))
   ((MOTHER NIL (CASUAL (POLE1) NIL)))
   ((MOTHER NIL (EGOTISTICAL (POLE2) NIL)))
   ((MOTHER NIL (EXUBERANT (POLE2) NIL)))
   ((MOTHER NIL (NOTTHEORIST (POLE1) NIL)))
   ((MOTHER NIL (LOVEX (POLE1) NIL)))
   ((MOTHER NIL (LOVEDANCE (POLE1) NIL)))
   ((MOTHER NIL (HELPINGCAREER (POLE2) NIL)))
   ((MOTHER NIL (HIGHIMPACT (POLE2) NIL)))))
 ("FATHER"
  "father"
  ELM3-1-1-99
  NIL
  NIL
  :BIPATHS
  (((FATHER NIL (CAREFOROTHERS (POLE2) NIL)))
   ((FATHER NIL (PSYCHOLOGISTS (POLE2) NIL)))
   ((FATHER NIL (UNDERSTANDING (POLE2) NIL)))
   ((FATHER NIL (IMPULSIVE (POLE1) NIL)))
   ((FATHER NIL (ENTERTAINER (POLE1) NIL)))
   ((FATHER NIL (AGGRESSIVE (POLE1) NIL)))
   ((FATHER NIL (PATERNAL (POLE1) NIL)))))
 ("BEST-M-FRIEND"
  "best-m-friend"
  ELM4-1-1-99
  NIL
  "DAVE"
  :BIPATHS
  (((BEST-M-FRIEND NIL (CAREFOROTHERS (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (INTIMATE (POLE2) NIL)))
   ((BEST-M-FRIEND NIL (PSYCHOLOGISTS (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (CAREABOUTOTHERSFEE (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (INSPIREOTHERS (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (BESTFRIEND (POLE2) NIL)))
   ((BEST-M-FRIEND NIL (DIRECT-HONEST (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (UNBRIDLEDHUMOR (POLE2) NIL)))
   ((BEST-M-FRIEND NIL (FANTASYWORLD (POLE2) NIL)))
   ((BEST-M-FRIEND NIL (ATHLETIC (POLE1) NIL)))
   ((BEST-M-FRIEND NIL (ESPOSECHRISTIAN (POLE2) NIL)))
   ((BEST-M-FRIEND NIL (CRITICAL (POLE2) NIL)))))
 ("BEST-F-FRIEND"
  "best-f-friend"
  ELM5-1-1-99
  NIL
  "JAN"
  :BIPATHS
  (((BEST-F-FRIEND NIL (INTIMATE (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (FLEXIBLE (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (UNDERSTANDING (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (CAREABOUTOTHERSFEE (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (SEXDEVIANCE (POLE2) NIL)))
   ((BEST-F-FRIEND NIL (GLOBALPERSPECTIVE (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (FUNCOMPANION (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (SELF-DISCLOSE (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (MISSIONSPREADPSYCH (POLE2) NIL)))
   ((BEST-F-FRIEND NIL (CRUEL (POLE2) NIL)))
   ((BEST-F-FRIEND NIL (COURTEOUS (POLE1) NIL)))
   ((BEST-F-FRIEND NIL (DEEPUNDERSTANDPEOP (POLE1) NIL)))))
 ("M-DISLIKE"
  "m-dislike"
  ELM6-1-1-99
  NIL
  "MICHAEL J"
  :BIPATHS
  (((M-DISLIKE NIL (CASUAL (POLE2) NIL)))
   ((M-DISLIKE NIL (IMPULSIVE (POLE1) NIL)))
   ((M-DISLIKE NIL (CAREABOUTOTHERSFEE (POLE2) NIL)))
   ((M-DISLIKE NIL (INSPIREOTHERS (POLE2) NIL)))
   ((M-DISLIKE NIL (SEXDEVIANCE (POLE1) NIL)))
   ((M-DISLIKE NIL (DEMOCRATICLEADER (POLE2) NIL)))
   ((M-DISLIKE NIL (PSYCHOLOGIST (POLE1) NIL)))
   ((M-DISLIKE NIL (METICULOUS (POLE1) NIL)))
   ((M-DISLIKE NIL (COGNITIVEPSYCHS (POLE1) NIL)))
   ((M-DISLIKE NIL (EMOTIONAL (POLE1) NIL)))
   ((M-DISLIKE NIL (CHARMING (POLE2) NIL)))))
 ("F-DISLIKE"
  "f-dislike"
  ELM7-1-1-99
  NIL
  "JUNE C"
  :BIPATHS
  (((F-DISLIKE NIL (FLEXIBLE (POLE2) NIL)))
   ((F-DISLIKE NIL (EGOTISTICAL (POLE1) NIL)))
   ((F-DISLIKE NIL (BESTFRIEND (POLE1) NIL)))
   ((F-DISLIKE NIL (GLOBALPERSPECTIVE (POLE2) NIL)))
   ((F-DISLIKE NIL (VALUEGROUPHAPPINES (POLE2) NIL)))
   ((F-DISLIKE NIL (LOCALLEADER (POLE1) NIL)))
   ((F-DISLIKE NIL (HIGHLYEDUCATED (POLE1) NIL)))
   ((F-DISLIKE NIL (ENLIGHTENWORLD (POLE2) NIL)))
   ((F-DISLIKE NIL (PETTY (POLE1) NIL)))
   ((F-DISLIKE NIL (ENCOURAGING (POLE2) NIL)))))
 ("M-ADMIRE"
  "m-admire"
  ELM8-1-1-99
  NIL
  "MAXSON"
  :BIPATHS
  (((M-ADMIRE NIL (EXUBERANT (POLE1) NIL)))
   ((M-ADMIRE NIL (DIRECT-HONEST (POLE1) NIL)))
   ((M-ADMIRE NIL (DEMOCRATICLEADER (POLE1) NIL)))
   ((M-ADMIRE NIL (VALUEGROUPHAPPINES (POLE1) NIL)))
   ((M-ADMIRE NIL (HUMOROUS (POLE1) NIL)))
   ((M-ADMIRE NIL (GREATLEADER (POLE1) NIL)))
   ((M-ADMIRE NIL (CONFIDENT-SELF-EST (POLE1) NIL)))
   ((M-ADMIRE NIL (INTERPERSONALSKILL (POLE1) NIL)))
   ((M-ADMIRE NIL (INTIMATELYASSERTIV (POLE1) NIL)))
   ((M-ADMIRE NIL (GREATSPEAKER (POLE2) NIL)))))
 ("F-ADMIRE"
  "f-admire"
  ELM9-1-1-99
  NIL
  "HILLARY C"
  :BIPATHS
  (((F-ADMIRE NIL (INSPIREOTHERS (POLE1) NIL)))
   ((F-ADMIRE NIL (FUNCOMPANION (POLE2) NIL)))
   ((F-ADMIRE NIL (DEMOCRATICLEADER (POLE1) NIL)))
   ((F-ADMIRE NIL (PSYCHOLOGIST (POLE2) NIL)))
   ((F-ADMIRE NIL (VALUEGROUPHAPPINES (POLE1) NIL)))
   ((F-ADMIRE NIL (LOCALLEADER (POLE2) NIL)))
   ((F-ADMIRE NIL (HUMOROUS (POLE2) NIL)))
   ((F-ADMIRE NIL (AUTONOMOUS (POLE1) NIL)))
   ((F-ADMIRE NIL (HIGHINTELLIGENCE (POLE1) NIL)))
   ((F-ADMIRE NIL (GOODNEGOTIATOR (POLE1) NIL)))
   ((F-ADMIRE NIL (PROGRESSIVE (POLE1) NIL)))))
 ("PER-MOSTFUN"
  "per-mostfun"
  ELM10-1-1-99
  NIL
  "LEE L"
  :BIPATHS
  (((PER-MOSTFUN NIL (CASUAL (POLE1) NIL)))
   ((PER-MOSTFUN NIL (NOTTHEORIST (POLE1) NIL)))
   ((PER-MOSTFUN NIL (UNBRIDLEDHUMOR (POLE1) NIL)))
   ((PER-MOSTFUN NIL (SELF-DISCLOSE (POLE1) NIL)))
   ((PER-MOSTFUN NIL (METICULOUS (POLE2) NIL)))
   ((PER-MOSTFUN NIL (HIGHLYEDUCATED (POLE2) NIL)))
   ((PER-MOSTFUN NIL (HUMOROUS (POLE1) NIL)))
   ((PER-MOSTFUN NIL (GREATLEADER (POLE2) NIL)))
   ((PER-MOSTFUN NIL (CLOSE (POLE1) NIL)))
   ((PER-MOSTFUN NIL (PLAYFUL (POLE1) NIL)))
   ((PER-MOSTFUN NIL (COUNSELORS (POLE2) NIL)))
   ((PER-MOSTFUN NIL (INDUSTRIOUS (POLE1) NIL)))))
 ("PER-ROMANCE"
  "per-romance"
  ELM11-1-1-99
  NIL
  "SHERRY"
  :BIPATHS
  (((PER-ROMANCE NIL (LOVEX (POLE1) NIL)))
   ((PER-ROMANCE NIL (UNBRIDLEDHUMOR (POLE1) NIL)))
   ((PER-ROMANCE NIL (FANTASYWORLD (POLE1) NIL)))
   ((PER-ROMANCE NIL (FUNCOMPANION (POLE1) NIL)))
   ((PER-ROMANCE NIL (AUTONOMOUS (POLE1) NIL)))
   ((PER-ROMANCE NIL (CLOSE (POLE1) NIL)))
   ((PER-ROMANCE NIL (SEXY (POLE1) NIL)))
   ((PER-ROMANCE NIL (UNDERSTANDING4 (POLE1) NIL)))
   ((PER-ROMANCE NIL (SOFTSPOKEN (POLE2) NIL)))))
 ("ROLE-MODEL"
  "role-model"
  ELM12-1-1-99
  NIL
  "STAATS"
  :BIPATHS
  (((ROLE-MODEL NIL (NOTTHEORIST (POLE2) NIL)))
   ((ROLE-MODEL NIL (ENTERTAINER (POLE2) NIL)))
   ((ROLE-MODEL NIL (MISSIONSPREADPSYCH (POLE1) NIL)))
   ((ROLE-MODEL NIL (COGNITIVEPSYCHS (POLE1) NIL)))
   ((ROLE-MODEL NIL (ENLIGHTENWORLD (POLE1) NIL)))
   ((ROLE-MODEL NIL (CONFIDENT-SELF-EST (POLE1) NIL)))
   ((ROLE-MODEL NIL (HIGHINTELLIGENCE (POLE1) NIL)))
   ((ROLE-MODEL NIL (SEXY (POLE2) NIL)))
   ((ROLE-MODEL NIL (TEAMMATE (POLE2) NIL)))
   ((ROLE-MODEL NIL (BEHAVIORALPSYCH (POLE1) NIL)))
   ((ROLE-MODEL NIL (OPTIMISTIC (POLE1) NIL)))))
 ("CHILD-FRIEND"
  "child-friend"
  ELM13-1-1-99
  NIL
  "JERRY R"
  :BIPATHS
  (((CHILD-FRIEND NIL (LOVEDANCE (POLE2) NIL)))
   ((CHILD-FRIEND NIL (BESTFRIEND (POLE1) NIL)))
   ((CHILD-FRIEND NIL (ATHLETIC (POLE1) NIL)))
   ((CHILD-FRIEND NIL (PLAYFUL (POLE1) NIL)))
   ((CHILD-FRIEND NIL (TEAMMATE (POLE1) NIL)))
   ((CHILD-FRIEND NIL (CHILDHOODFRIEND (POLE1) NIL)))
   ((CHILD-FRIEND NIL (DEBONAIRE (POLE2) NIL)))))
 ("CHILD-DISLIKE"
  "child-dislike"
  ELM14-1-1-99
  NIL
  "MIKE F"
  :BIPATHS
  (((CHILD-DISLIKE NIL (EGOTISTICAL (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (AGGRESSIVE (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (CRUEL (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (EMOTIONAL (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (PETTY (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (CONFIDENT-SELF-EST (POLE2) NIL)))
   ((CHILD-DISLIKE NIL (INTERPERSONALSKILL (POLE2) NIL)))
   ((CHILD-DISLIKE NIL (AUTONOMOUS (POLE2) NIL)))
   ((CHILD-DISLIKE NIL (UNDERSTANDING4 (POLE2) NIL)))
   ((CHILD-DISLIKE NIL (TEAMMATE (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (CHILDHOODFRIEND (POLE1) NIL)))
   ((CHILD-DISLIKE NIL (HIGHSTANDARDS (POLE2) NIL)))
   ((CHILD-DISLIKE NIL (TEACHER1 (POLE2) NIL)))))
 ("WORK-FRIEND"
  "work-friend"
  ELM15-1-1-99
  NIL
  "BOB C"
  :BIPATHS
  (((WORK-FRIEND NIL (HELPINGCAREER (POLE1) NIL)))
   ((WORK-FRIEND NIL (PSYCHOLOGISTS (POLE1) NIL)))
   ((WORK-FRIEND NIL (ESPOSECHRISTIAN (POLE1) NIL)))
   ((WORK-FRIEND NIL (MISSIONSPREADPSYCH (POLE1) NIL)))
   ((WORK-FRIEND NIL (PSYCHOLOGIST (POLE1) NIL)))
   ((WORK-FRIEND NIL (LOCALLEADER (POLE1) NIL)))
   ((WORK-FRIEND NIL (INTERPERSONALSKILL (POLE1) NIL)))
   ((WORK-FRIEND NIL (GOODNEGOTIATOR (POLE1) NIL)))
   ((WORK-FRIEND NIL (PLAYFUL (POLE2) NIL)))
   ((WORK-FRIEND NIL (COUNSELORS (POLE1) NIL)))
   ((WORK-FRIEND NIL (BEHAVIORALPSYCH (POLE1) NIL)))
   ((WORK-FRIEND NIL (HIGHSTANDARDS (POLE1) NIL)))
   ((WORK-FRIEND NIL (LIBERALCHRISTIAN (POLE1) NIL)))
   ((WORK-FRIEND NIL (EMPATHETICLISTENER (POLE1) NIL)))))
 ("WORK-PER-DISLIKE"
  "work-per-dislike"
  ELM16-1-1-99
  NIL
  "HISTORY PROF"
  :BIPATHS
  (((WORK-PER-DISLIKE NIL (SEXDEVIANCE (POLE1) NIL)))
   ((WORK-PER-DISLIKE NIL (CRUEL (POLE1) NIL)))
   ((WORK-PER-DISLIKE NIL (COURTEOUS (POLE2) NIL)))
   ((WORK-PER-DISLIKE NIL (INTIMATELYASSERTIV (POLE2) NIL)))
   ((WORK-PER-DISLIKE NIL (GOODNEGOTIATOR (POLE2) NIL)))
   ((WORK-PER-DISLIKE NIL (CLOSE (POLE2) NIL)))
   ((WORK-PER-DISLIKE NIL (HIGHSTANDARDS (POLE1) NIL)))
   ((WORK-PER-DISLIKE NIL (LIBERALCHRISTIAN (POLE2) NIL)))
   ((WORK-PER-DISLIKE NIL (OVERCOMEDIFFICULTI (POLE2) NIL)))))
 ("FAV-BOSS"
  "fav-boss"
  ELM17-1-1-99
  NIL
  "KEN W"
  :BIPATHS
  (((FAV-BOSS NIL (UNDERSTANDING (POLE1) NIL)))
   ((FAV-BOSS NIL (PATERNAL (POLE1) NIL)))
   ((FAV-BOSS NIL (CHARMING (POLE1) NIL)))
   ((FAV-BOSS NIL (ENCOURAGING (POLE1) NIL)))
   ((FAV-BOSS NIL (GREATLEADER (POLE1) NIL)))
   ((FAV-BOSS NIL (PROGRESSIVE (POLE1) NIL)))
   ((FAV-BOSS NIL (SOFTSPOKEN (POLE1) NIL)))
   ((FAV-BOSS NIL (BEHAVIORALPSYCH (POLE2) NIL)))
   ((FAV-BOSS NIL (DEBONAIRE (POLE1) NIL)))
   ((FAV-BOSS NIL (TEACHER1 (POLE1) NIL)))))
 ("WORST-BOSS"
  "worst-boss"
  ELM18-1-1-99
  NIL
  "CLYDE C"
  :BIPATHS
  (((WORST-BOSS NIL (DIRECT-HONEST (POLE2) NIL)))
   ((WORST-BOSS NIL (ATHLETIC (POLE2) NIL)))
   ((WORST-BOSS NIL (CRITICAL (POLE1) NIL)))
   ((WORST-BOSS NIL (SELF-DISCLOSE (POLE2) NIL)))
   ((WORST-BOSS NIL (COUNSELORS (POLE1) NIL)))
   ((WORST-BOSS NIL (INDUSTRIOUS (POLE1) NIL)))
   ((WORST-BOSS NIL (OPTIMISTIC (POLE2) NIL)))
   ((WORST-BOSS NIL (FIGHTILLNESS (POLE1) NIL)))))
 ("FAV-M-STAR"
  "fav-m-star"
  ELM19-1-1-99
  NIL
  "FRED ASTAIRE"
  :BIPATHS
  (((FAV-M-STAR NIL (EXUBERANT (POLE1) NIL)))
   ((FAV-M-STAR NIL (LOVEDANCE (POLE1) NIL)))
   ((FAV-M-STAR NIL (HIGHIMPACT (POLE1) NIL)))
   ((FAV-M-STAR NIL (ENTERTAINER (POLE1) NIL)))
   ((FAV-M-STAR NIL (PATERNAL (POLE2) NIL)))
   ((FAV-M-STAR NIL (FANTASYWORLD (POLE1) NIL)))
   ((FAV-M-STAR NIL (COGNITIVEPSYCHS (POLE2) NIL)))
   ((FAV-M-STAR NIL (CHARMING (POLE1) NIL)))
   ((FAV-M-STAR NIL (ENLIGHTENWORLD (POLE1) NIL)))
   ((FAV-M-STAR NIL (ENCOURAGING (POLE1) NIL)))
   ((FAV-M-STAR NIL (SEXY (POLE1) NIL)))
   ((FAV-M-STAR NIL (SOFTSPOKEN (POLE1) NIL)))
   ((FAV-M-STAR NIL (OPTIMISTIC (POLE1) NIL)))
   ((FAV-M-STAR NIL (DEBONAIRE (POLE1) NIL)))
   ((FAV-M-STAR NIL (FIGHTILLNESS (POLE2) NIL)))))
 ("FAV-POLITICO"
  "fav-politico"
  ELM20-1-1-99
  NIL
  "FDR"
  :BIPATHS
  (((FAV-POLITICO NIL (LOVEX (POLE2) NIL)))
   ((FAV-POLITICO NIL (HIGHIMPACT (POLE1) NIL)))
   ((FAV-POLITICO NIL (IMPULSIVE (POLE2) NIL)))
   ((FAV-POLITICO NIL (AGGRESSIVE (POLE2) NIL)))
   ((FAV-POLITICO NIL (GLOBALPERSPECTIVE (POLE1) NIL)))
   ((FAV-POLITICO NIL (DEEPUNDERSTANDPEOP (POLE1) NIL)))
   ((FAV-POLITICO NIL (EMOTIONAL (POLE2) NIL)))
   ((FAV-POLITICO NIL (PETTY (POLE2) NIL)))
   ((FAV-POLITICO NIL (INTIMATELYASSERTIV (POLE1) NIL)))
   ((FAV-POLITICO NIL (GREATSPEAKER (POLE1) NIL)))
   ((FAV-POLITICO NIL (INDUSTRIOUS (POLE2) NIL)))
   ((FAV-POLITICO NIL (UNDERSTANDING4 (POLE1) NIL)))
   ((FAV-POLITICO NIL (CHILDHOODFRIEND (POLE2) NIL)))
   ((FAV-POLITICO NIL (EMPATHETICLISTENER (POLE1) NIL)))
   ((FAV-POLITICO NIL (OVERCOMEDIFFICULTI (POLE1) NIL)))
   ((FAV-POLITICO NIL (FIGHTILLNESS (POLE1) NIL)))))
 ("FAV-TEACHER"
  "fav-teacher"
  ELM21-1-1-99
  NIL
  "COBB"
  :BIPATHS
  (((FAV-TEACHER NIL (ESPOSECHRISTIAN (POLE1) NIL)))
   ((FAV-TEACHER NIL (COURTEOUS (POLE1) NIL)))
   ((FAV-TEACHER NIL (LIBERALCHRISTIAN (POLE1) NIL)))))
 ("FAV-SPIRITUAL"
  "fav-spiritual"
  ELM22-1-1-99
  NIL
  "STOWE"
  :BIPATHS
  (((FAV-SPIRITUAL NIL (HELPINGCAREER (POLE1) NIL)))
   ((FAV-SPIRITUAL NIL (METICULOUS (POLE1) NIL)))
   ((FAV-SPIRITUAL NIL (HIGHLYEDUCATED (POLE1) NIL)))
   ((FAV-SPIRITUAL NIL (GREATSPEAKER (POLE1) NIL)))
   ((FAV-SPIRITUAL NIL (OVERCOMEDIFFICULTI (POLE1) NIL)))))
 ("DIS-TEACHER"
  "dis-teacher"
  ELM23-1-1-99
  NIL
  "RILEY"
  :BIPATHS
  (((DIS-TEACHER NIL (CRITICAL (POLE1) NIL)))
   ((DIS-TEACHER NIL (DEEPUNDERSTANDPEOP (POLE2) NIL)))
   ((DIS-TEACHER NIL (HIGHINTELLIGENCE (POLE2) NIL)))
   ((DIS-TEACHER NIL (PROGRESSIVE (POLE2) NIL)))
   ((DIS-TEACHER NIL (TEACHER1 (POLE1) NIL)))
   ((DIS-TEACHER NIL (EMPATHETICLISTENER (POLE2) NIL)))))
 ("TEACHER"
  "teacher"
  ELM2-1-1-99
  NIL
  NIL
  :BIPATHS
  (((TEACHER NIL (PUBLICSERVANT (POLE1) NIL)))
   ((TEACHER NIL (SECULAR (POLE1) NIL)))
   ((TEACHER NIL (SEEKATTENTION (POLE2) NIL)))
   ((TEACHER NIL (HELPER (POLE1) NIL)))
   ((TEACHER NIL (SPREADKNOWLEDGE (POLE1) NIL)))
   ((TEACHER NIL (LAWFUL (POLE1) NIL)))
   ((TEACHER NIL (MANAGER0 (POLE1) NIL)))
   ((TEACHER NIL (PRAGMATIC (POLE1) NIL)))
   ((TEACHER NIL (GROUPKNOWLEDGEWORK (POLE1) NIL)))
   ((TEACHER NIL (VERBALSKILLS (POLE1) NIL)))
   ((TEACHER NIL (LESSCIVILIZED (POLE2) NIL)))
   ((TEACHER NIL (REPRESENTGROUP (POLE1) NIL)))
   ((TEACHER NIL (PERFORMER (POLE1) NIL)))
   ((TEACHER NIL (SHOWBUSINESS (POLE2) NIL)))
   ((TEACHER NIL (SOLVEPROBLEMS (POLE1) NIL)))
   ((TEACHER NIL (STARPERFORMER (POLE2) NIL)))
   ((TEACHER NIL (LESSWEALTH (POLE1) NIL)))
   ((TEACHER NIL (DEPENDGOV (POLE1) NIL)))
   ((TEACHER NIL (IMMIGRANTS (POLE2) NIL)))))
 ("POLICEMAN"
  "policeman"
  ELM3-1-1-99
  NIL
  NIL
  :BIPATHS
  (((POLICEMAN NIL (PUBLICSERVANT (POLE1) NIL)))
   ((POLICEMAN NIL (SECULAR (POLE1) NIL)))
   ((POLICEMAN NIL (PROFIT-ORIENTED (POLE2) NIL)))
   ((POLICEMAN NIL (OCCUPATION (POLE1) NIL)))
   ((POLICEMAN NIL (PHYSICALWELLBEING (POLE1) NIL)))
   ((POLICEMAN NIL (LEGALEXPERT (POLE1) NIL)))
   ((POLICEMAN NIL (SELF-DISCIPLINE (POLE1) NIL)))
   ((POLICEMAN NIL (ENFORCERULES (POLE2) NIL)))
   ((POLICEMAN NIL (CREATENEWRULES (POLE2) NIL)))
   ((POLICEMAN NIL (SOCIALCONSTRAINTS (POLE1) NIL)))
   ((POLICEMAN NIL (RESPECTED (POLE1) NIL)))
   ((POLICEMAN NIL (SEEKEXTERNALAPPROV (POLE2) NIL)))
   ((POLICEMAN NIL (CREATIVE (POLE2) NIL)))
   ((POLICEMAN NIL (RITUALISTIC (POLE1) NIL)))
   ((POLICEMAN NIL (LESSMORALISTIC (POLE2) NIL)))
   ((POLICEMAN NIL (PROFESSIONAL (POLE1) NIL)))
   ((POLICEMAN NIL (DRAMATIC (POLE2) NIL)))
   ((POLICEMAN NIL (EUROCENTRICVALUES (POLE2) NIL)))
   ((POLICEMAN NIL (INDIVIDUALISTIC (POLE1) NIL)))
   ((POLICEMAN NIL (CATHOLIC (POLE1) NIL)))))
 ("SALESPERSON"
  "salesperson"
  ELM4-1-1-99
  NIL
  NIL
  :BIPATHS
  (((SALESPERSON NIL (PUBLICSERVANT (POLE2) NIL)))
   ((SALESPERSON NIL (SEEKATTENTION (POLE1) NIL)))
   ((SALESPERSON NIL (PROFIT-ORIENTED (POLE1) NIL)))
   ((SALESPERSON NIL (OCCUPATION (POLE1) NIL)))
   ((SALESPERSON NIL (PEOPLE-JOB (POLE1) NIL)))
   ((SALESPERSON NIL (GREEDY (POLE1) NIL)))
   ((SALESPERSON NIL (OWNER (POLE2) NIL)))
   ((SALESPERSON NIL (PERFORMANCE-ORIENT (POLE1) NIL)))
   ((SALESPERSON NIL (HIGHSTATUS (POLE1) NIL)))
   ((SALESPERSON NIL (RATIONAL (POLE2) NIL)))
   ((SALESPERSON NIL (PRACTICAL (POLE2) NIL)))
   ((SALESPERSON NIL (PERSUASIVE (POLE1) NIL)))
   ((SALESPERSON NIL (INFLUENCIAL (POLE1) NIL)))
   ((SALESPERSON NIL (MANUALWORK (POLE2) NIL)))
   ((SALESPERSON NIL (NOTHISTORY-ORIENTE (POLE1) NIL)))
   ((SALESPERSON NIL (NOTANALYTIC (POLE1) NIL)))
   ((SALESPERSON NIL (NOTLOYAL (POLE1) NIL)))
   ((SALESPERSON NIL (SPIRITUALINTEGRATI (POLE2) NIL)))
   ((SALESPERSON NIL (SEEKULTIMATETRUTH (POLE2) NIL)))
   ((SALESPERSON NIL (MATERIALISTIC (POLE1) NIL)))))
 ("DOCTOR"
  "doctor"
  ELM5-1-1-99
  NIL
  NIL
  :BIPATHS
  (((DOCTOR NIL (HELPER (POLE1) NIL)))
   ((DOCTOR NIL (PHYSICALWELLBEING (POLE1) NIL)))
   ((DOCTOR NIL (PEOPLE-JOB (POLE1) NIL)))
   ((DOCTOR NIL (SKILLEDMOVEMENTS (POLE1) NIL)))))
 ("LAWYER"
  "lawyer"
  ELM6-1-1-99
  NIL
  NIL
  :BIPATHS
  (((LAWYER NIL (SPREADKNOWLEDGE (POLE2) NIL)))
   ((LAWYER NIL (LAWFUL (POLE1) NIL)))
   ((LAWYER NIL (LEGALEXPERT (POLE1) NIL)))
   ((LAWYER NIL (GREEDY (POLE1) NIL)))
   ((LAWYER NIL (SKILLEDMOVEMENTS (POLE2) NIL)))))
 ("BUSINESS-OWNER"
  "business-owner"
  ELM7-1-1-99
  NIL
  NIL
  :BIPATHS
  (((BUSINESS-OWNER NIL (MANAGER0 (POLE1) NIL)))
   ((BUSINESS-OWNER NIL (PROFIT-ORIENTED (POLE1) NIL)))
   ((BUSINESS-OWNER NIL (SELF-DISCIPLINE (POLE1) NIL)))
   ((BUSINESS-OWNER NIL (OWNER (POLE1) NIL)))
   ((BUSINESS-OWNER NIL (PERFORMANCE-ORIENT (POLE1) NIL)))))
 ("MANAGER"
  "manager"
  ELM8-1-1-99
  NIL
  NIL
  :BIPATHS
  (((MANAGER NIL (PRAGMATIC (POLE1) NIL)))
   ((MANAGER NIL (ENFORCERULES (POLE1) NIL)))
   ((MANAGER NIL (HIGHSTATUS (POLE1) NIL)))))
 ("SCIENTIST"
  "scientist"
  ELM9-1-1-99
  NIL
  NIL
  :BIPATHS
  (((SCIENTIST NIL (SPREADKNOWLEDGE (POLE1) NIL)))
   ((SCIENTIST NIL (GROUPKNOWLEDGEWORK (POLE1) NIL)))
   ((SCIENTIST NIL (CREATENEWRULES (POLE1) NIL)))
   ((SCIENTIST NIL (RATIONAL (POLE1) NIL)))))
 ("FARMER"
  "farmer"
  ELM10-1-1-99
  NIL
  NIL
  :BIPATHS
  (((FARMER NIL (VERBALSKILLS (POLE2) NIL)))
   ((FARMER NIL (SOCIALCONSTRAINTS (POLE2) NIL)))
   ((FARMER NIL (OWNER (POLE1) NIL)))
   ((FARMER NIL (PRACTICAL (POLE1) NIL)))))
 ("DRUG-DEALER"
  "drug dealer"
  ELM11-1-1-99
  NIL
  NIL
  :BIPATHS
  (((DRUG-DEALER NIL (LESSCIVILIZED (POLE1) NIL)))
   ((DRUG-DEALER NIL (RESPECTED (POLE2) NIL)))
   ((DRUG-DEALER NIL (PERSUASIVE (POLE1) NIL)))))
 ("POLITICIAN"
  "politician"
  ELM12-1-1-99
  NIL
  NIL
  :BIPATHS
  (((POLITICIAN NIL (REPRESENTGROUP (POLE1) NIL)))
   ((POLITICIAN NIL (CREATENEWRULES (POLE1) NIL)))
   ((POLITICIAN NIL (SOCIALCONSTRAINTS (POLE1) NIL)))
   ((POLITICIAN NIL (SEEKEXTERNALAPPROV (POLE1) NIL)))
   ((POLITICIAN NIL (INFLUENCIAL (POLE1) NIL)))))
 ("DANCER"
  "dancer"
  ELM13-1-1-99
  NIL
  NIL
  :BIPATHS
  (((DANCER NIL (HELPER (POLE2) NIL)))
   ((DANCER NIL (PERFORMER (POLE1) NIL)))
   ((DANCER NIL (ENFORCERULES (POLE1) NIL)))
   ((DANCER NIL (RESPECTED (POLE1) NIL)))
   ((DANCER NIL (CREATIVE (POLE1) NIL)))
   ((DANCER NIL (GREEDY (POLE2) NIL)))
   ((DANCER NIL (SKILLEDMOVEMENTS (POLE1) NIL)))))
 ("ARTIST"
  "artist"
  ELM14-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ARTIST NIL (RITUALISTIC (POLE2) NIL)))
   ((ARTIST NIL (MANUALWORK (POLE1) NIL)))))
 ("COMEDIAN"
  "comedian"
  ELM15-1-1-99
  NIL
  NIL
  :BIPATHS
  (((COMEDIAN NIL (SHOWBUSINESS (POLE1) NIL)))
   ((COMEDIAN NIL (SELF-DISCIPLINE (POLE2) NIL)))
   ((COMEDIAN NIL (SEEKEXTERNALAPPROV (POLE1) NIL)))
   ((COMEDIAN NIL (LESSMORALISTIC (POLE1) NIL)))
   ((COMEDIAN NIL (NOTHISTORY-ORIENTE (POLE1) NIL)))))
 ("ENGINEER"
  "engineer"
  ELM16-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ENGINEER NIL (SOLVEPROBLEMS (POLE1) NIL)))
   ((ENGINEER NIL (NOTANALYTIC (POLE2) NIL)))))
 ("HOUSE-CLEANER"
  "house cleaner"
  ELM17-1-1-99
  NIL
  NIL
  :BIPATHS
  (((HOUSE-CLEANER NIL (PROFESSIONAL (POLE2) NIL)))
   ((HOUSE-CLEANER NIL (PEOPLE-JOB (POLE2) NIL)))
   ((HOUSE-CLEANER NIL (MANUALWORK (POLE1) NIL)))))
 ("MOVIE-STAR"
  "movie-star"
  ELM18-1-1-99
  NIL
  NIL
  :BIPATHS
  (((MOVIE-STAR NIL (SEEKATTENTION (POLE1) NIL)))
   ((MOVIE-STAR NIL (SHOWBUSINESS (POLE1) NIL)))
   ((MOVIE-STAR NIL (STARPERFORMER (POLE1) NIL)))
   ((MOVIE-STAR NIL (LEGALEXPERT (POLE2) NIL)))
   ((MOVIE-STAR NIL (CREATIVE (POLE1) NIL)))
   ((MOVIE-STAR NIL (DRAMATIC (POLE1) NIL)))
   ((MOVIE-STAR NIL (NOTLOYAL (POLE1) NIL)))))
 ("ROCK-STAR"
  "rock-star"
  ELM19-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ROCK-STAR NIL (STARPERFORMER (POLE1) NIL)))
   ((ROCK-STAR NIL (LESSWEALTH (POLE2) NIL)))))
 ("CHURCH-MINISTER"
  "church-minister"
  ELM20-1-1-99
  NIL
  NIL
  :BIPATHS
  (((CHURCH-MINISTER NIL (PROFESSIONAL (POLE1) NIL)))
   ((CHURCH-MINISTER NIL (EUROCENTRICVALUES (POLE1) NIL)))
   ((CHURCH-MINISTER NIL (SPIRITUALINTEGRATI (POLE1) NIL)))))
 ("CATHOLICS"
  "catholics"
  ELM21-1-1-99
  NIL
  NIL
  :BIPATHS
  (((CATHOLICS NIL (DEPENDGOV (POLE2) NIL)))))
 ("PROTESTANTS"
  "protestants"
  ELM22-1-1-99
  NIL
  NIL
  :BIPATHS
  (((PROTESTANTS NIL (PHYSICALWELLBEING (POLE2) NIL)))
   ((PROTESTANTS NIL (RITUALISTIC (POLE1) NIL)))
   ((PROTESTANTS NIL (INDIVIDUALISTIC (POLE2) NIL)))
   ((PROTESTANTS NIL (NOTHISTORY-ORIENTE (POLE2) NIL)))
   ((PROTESTANTS NIL (SPIRITUALINTEGRATI (POLE1) NIL)))
   ((PROTESTANTS NIL (SEEKULTIMATETRUTH (POLE1) NIL)))))
 ("JEWS"
  "jews"
  ELM23-1-1-99
  NIL
  NIL
  :BIPATHS
  (((JEWS NIL (GROUPKNOWLEDGEWORK (POLE2) NIL)))
   ((JEWS NIL (VERBALSKILLS (POLE1) NIL)))
   ((JEWS NIL (NOTLOYAL (POLE2) NIL)))))
 ("MUSLIMS"
  "muslims"
  ELM24-1-1-99
  NIL
  NIL
  :BIPATHS
  (((MUSLIMS NIL (SECULAR (POLE2) NIL)))
   ((MUSLIMS NIL (PRAGMATIC (POLE2) NIL)))
   ((MUSLIMS NIL (LESSCIVILIZED (POLE1) NIL)))
   ((MUSLIMS NIL (SOLVEPROBLEMS (POLE2) NIL)))
   ((MUSLIMS NIL (IMMIGRANTS (POLE1) NIL)))))
 ("BUDDHISTS"
  "buddhists"
  ELM25-1-1-99
  NIL
  NIL
  :BIPATHS
  (((BUDDHISTS NIL (SEEKULTIMATETRUTH (POLE1) NIL)))
   ((BUDDHISTS NIL (MATERIALISTIC (POLE2) NIL)))))
 ("ATHEISTS"
  "atheists"
  ELM26-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ATHEISTS NIL (MANAGER0 (POLE2) NIL)))
   ((ATHEISTS NIL (REPRESENTGROUP (POLE2) NIL)))
   ((ATHEISTS NIL (CATHOLIC (POLE2) NIL)))))
 ("ANGLOS"
  "Anglos"
  ELM27-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ANGLOS NIL (OCCUPATION (POLE2) NIL)))
   ((ANGLOS NIL (LESSMORALISTIC (POLE1) NIL)))
   ((ANGLOS NIL (EUROCENTRICVALUES (POLE1) NIL)))
   ((ANGLOS NIL (RATIONAL (POLE1) NIL)))
   ((ANGLOS NIL (PRACTICAL (POLE1) NIL)))
   ((ANGLOS NIL (MATERIALISTIC (POLE1) NIL)))))
 ("HISPANICS"
  "Hispanics"
  ELM28-1-1-99
  NIL
  NIL
  :BIPATHS
  (((HISPANICS NIL (LESSWEALTH (POLE1) NIL)))
   ((HISPANICS NIL (IMMIGRANTS (POLE1) NIL)))
   ((HISPANICS NIL (DRAMATIC (POLE1) NIL)))
   ((HISPANICS NIL (CATHOLIC (POLE1) NIL)))
   ((HISPANICS NIL (HIGHSTATUS (POLE2) NIL)))
   ((HISPANICS NIL (PERSUASIVE (POLE2) NIL)))
   ((HISPANICS NIL (NOTANALYTIC (POLE1) NIL)))))
 ("BLACKS"
  "Blacks"
  ELM29-1-1-99
  NIL
  NIL
  :BIPATHS
  (((BLACKS NIL (LAWFUL (POLE2) NIL)))
   ((BLACKS NIL (PERFORMER (POLE2) NIL)))
   ((BLACKS NIL (DEPENDGOV (POLE1) NIL)))))
 ("ASIANS"
  "Asians"
  ELM30-1-1-99
  NIL
  NIL
  :BIPATHS
  (((ASIANS NIL (INDIVIDUALISTIC (POLE1) NIL)))
   ((ASIANS NIL (PERFORMANCE-ORIENT (POLE2) NIL)))
   ((ASIANS NIL (INFLUENCIAL (POLE2) NIL)))))
 ("MOST-IMPORTANT-VALUE" "Most-Important-Value" ELM2-1-1-99 NIL "HAPPINESS")
 ("MOST-IMPORTANT-ABILITY" "Most-Important-Ability" ELM3-1-1-99 NIL "HQ")
 ("MOST-IMPORTANT-BELIEF"
  "Most-Important-Belief"
  ELM4-1-1-99
  NIL
  "HAPPY TOP GOAL FOR ALL BEST")
 ("YOUR-PERSONALITY" "Your-Personality" ELM5-1-1-99 NIL "INTEGRITY")
 ("YOUR-BEST-CHARACTERISTIC"
  "Your-Best-Characteristic"
  ELM6-1-1-99
  NIL
  "RESOURCEFUL")
 ("YOUR-POSSESSIONS" "Your-Possessions" ELM7-1-1-99 NIL "WEALTHY")
 ("YOUR-WORST-CHARACTERISTIC"
  "Your-Worst-Characteristic"
  ELM8-1-1-99
  NIL
  "TEMPER"))
  )