;;(pprint *file-pcsymval-lists)

(setf *file-pcsymval-lists
'((CAREFOROTHERS
  ("CAREFOROTHERS"
   "CARE FOR OTHERS vs SELFISH"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CARE FOR OTHERS" "SELFISH" 1 NIL)
   :POLE1
   "CARE FOR OTHERS"
   :POLE2
   "SELFISH"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL BEST-M-FRIEND NIL)
     (POLE2 NIL FATHER NIL)))))
 (INTIMATE
  ("INTIMATE"
   "INTIMATE vs NOT INTIMATE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INTIMATE" "NOT INTIMATE" 1 NIL)
   :POLE1
   "INTIMATE"
   :POLE2
   "NOT INTIMATE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL BEST-F-FRIEND NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (FLEXIBLE
  ("FLEXIBLE"
   "FLEXIBLE vs RIGID"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("FLEXIBLE" "RIGID" 1 NIL)
   :POLE1
   "FLEXIBLE"
   :POLE2
   "RIGID"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL BEST-F-FRIEND NIL)
     (POLE2 NIL F-DISLIKE NIL)))))
 (CASUAL
  ("CASUAL"
   "CASUAL vs FORMAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CASUAL" "FORMAL" 1 NIL)
   :POLE1
   "CASUAL"
   :POLE2
   "FORMAL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL PER-MOSTFUN NIL)
     (POLE2 NIL M-DISLIKE NIL)))))
 (EGOTISTICAL
  ("EGOTISTICAL"
   "EGOTISTICAL vs HUMBLE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("EGOTISTICAL" "HUMBLE" 2 NIL)
   :POLE1
   "EGOTISTICAL"
   :POLE2
   "HUMBLE"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL F-DISLIKE NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL MOTHER NIL)))))
 (EXUBERANT
  ("EXUBERANT"
   "EXUBERANT vs INHIBITED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("EXUBERANT" "INHIBITED" 1 NIL)
   :POLE1
   "EXUBERANT"
   :POLE2
   "INHIBITED"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL MOTHER NIL)))))
 (NOTTHEORIST
  ("NOTTHEORIST"
   "NOT THEORIST vs ACCOMPLISHED THEORIST"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("NOT THEORIST" "ACCOMPLISHED THEORIST" 2 NIL)
   :POLE1
   "NOT THEORIST"
   :POLE2
   "ACCOMPLISHED THEORIST"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL PER-MOSTFUN NIL)
     (POLE2 NIL ROLE-MODEL NIL)))))
 (LOVEX
  ("LOVEX"
   "LOVE ME vs INDIFFERENT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LOVE ME" "INDIFFERENT" 1 NIL)
   :POLE1
   "LOVE ME"
   :POLE2
   "INDIFFERENT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL PER-ROMANCE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (LOVEDANCE
  ("LOVEDANCE"
   "LOVE DANCE vs NOT LOVE DANCE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LOVE DANCE" "NOT LOVE DANCE" 1 NIL)
   :POLE1
   "LOVE DANCE"
   :POLE2
   "NOT LOVE DANCE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOTHER NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL CHILD-FRIEND NIL)))))
 (HELPINGCAREER
  ("HELPINGCAREER"
   "HELPING CAREER vs NOT HELPING CAREER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HELPING CAREER" "NOT HELPING CAREER" 1 NIL)
   :POLE1
   "HELPING CAREER"
   :POLE2
   "NOT HELPING CAREER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL FAV-SPIRITUAL NIL)
     (POLE2 NIL MOTHER NIL)))))
 (HIGHIMPACT
  ("HIGHIMPACT"
   "HIGH IMPACT vs LO IMPACT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HIGH IMPACT" "LO IMPACT" 1 NIL)
   :POLE1
   "HIGH IMPACT"
   :POLE2
   "LO IMPACT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-M-STAR NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL MOTHER NIL)))))
 (PSYCHOLOGISTS
  ("PSYCHOLOGISTS"
   "PSYCHOLOGISTS vs NOT PSYCH"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PSYCHOLOGISTS" "NOT PSYCH" 1 NIL)
   :POLE1
   "PSYCHOLOGISTS"
   :POLE2
   "NOT PSYCH"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-M-FRIEND NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL FATHER NIL)))))
 (UNDERSTANDING
  ("UNDERSTANDING"
   "UNDERSTANDING vs NOT UNDERSTANDING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("UNDERSTANDING" "NOT UNDERSTANDING" 1 NIL)
   :POLE1
   "UNDERSTANDING"
   :POLE2
   "NOT UNDERSTANDING"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL FAV-BOSS NIL)
     (POLE2 NIL FATHER NIL)))))
 (IMPULSIVE
  ("IMPULSIVE"
   "IMPULSIVE vs NOT IMPULSIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("IMPULSIVE" "NOT IMPULSIVE" 2 NIL)
   :POLE1
   "IMPULSIVE"
   :POLE2
   "NOT IMPULSIVE"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL FATHER NIL)
     (POLE1 NIL M-DISLIKE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (ENTERTAINER
  ("ENTERTAINER"
   "ENTERTAINER vs NOT ENTERTAINER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ENTERTAINER" "NOT ENTERTAINER" 1 NIL)
   :POLE1
   "ENTERTAINER"
   :POLE2
   "NOT ENTERTAINER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FATHER NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL ROLE-MODEL NIL)))))
 (AGGRESSIVE
  ("AGGRESSIVE"
   "AGGRESSIVE vs CALM-ASSERTIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("AGGRESSIVE" "CALM-ASSERTIVE" 2 NIL)
   :POLE1
   "AGGRESSIVE"
   :POLE2
   "CALM-ASSERTIVE"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL FATHER NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (PATERNAL
  ("PATERNAL"
   "PATERNAL vs NOT PATERNAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PATERNAL" "NOT PATERNAL" 0 NIL)
   :POLE1
   "PATERNAL"
   :POLE2
   "NOT PATERNAL"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL FATHER NIL)
     (POLE1 NIL FAV-BOSS NIL)
     (POLE2 NIL FAV-M-STAR NIL)))))
 (CAREABOUTOTHERSFEE
  ("CAREABOUTOTHERSFEE"
   "CARE ABOUT OTHERS FEELINGS vs NOT CARE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CARE ABOUT OTHERS FEELINGS" "NOT CARE" 1 NIL)
   :POLE1
   "CARE ABOUT OTHERS FEELINGS"
   :POLE2
   "NOT CARE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-M-FRIEND NIL)
     (POLE1 NIL BEST-F-FRIEND NIL)
     (POLE2 NIL M-DISLIKE NIL)))))
 (INSPIREOTHERS
  ("INSPIREOTHERS"
   "INSPIRE OTHERS vs NOT INSPIRE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INSPIRE OTHERS" "NOT INSPIRE" 1 NIL)
   :POLE1
   "INSPIRE OTHERS"
   :POLE2
   "NOT INSPIRE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-M-FRIEND NIL)
     (POLE1 NIL F-ADMIRE NIL)
     (POLE2 NIL M-DISLIKE NIL)))))
 (BESTFRIEND
  ("BESTFRIEND"
   "BEST FRIEND vs ENEMY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("BEST FRIEND" "ENEMY" 1 NIL)
   :POLE1
   "BEST FRIEND"
   :POLE2
   "ENEMY"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-DISLIKE NIL)
     (POLE1 NIL CHILD-FRIEND NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (DIRECT-HONEST
  ("DIRECT-HONEST"
   "DIRECT-HONEST vs SNEAKY-GAMES"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DIRECT-HONEST" "SNEAKY-GAMES" 1 NIL)
   :POLE1
   "DIRECT-HONEST"
   :POLE2
   "SNEAKY-GAMES"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-M-FRIEND NIL)
     (POLE1 NIL M-ADMIRE NIL)
     (POLE2 NIL WORST-BOSS NIL)))))
 (UNBRIDLEDHUMOR
  ("UNBRIDLEDHUMOR"
   "UNBRIDLED HUMOR vs PC-KIND-HUMOR"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("UNBRIDLED HUMOR" "PC-KIND-HUMOR" 0 NIL)
   :POLE1
   "UNBRIDLED HUMOR"
   :POLE2
   "PC-KIND-HUMOR"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL PER-MOSTFUN NIL)
     (POLE1 NIL PER-ROMANCE NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (FANTASYWORLD
  ("FANTASYWORLD"
   "FANTASY WORLD vs REALISTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("FANTASY WORLD" "REALISTIC" 0 NIL)
   :POLE1
   "FANTASY WORLD"
   :POLE2
   "REALISTIC"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL PER-ROMANCE NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (ATHLETIC
  ("ATHLETIC"
   "ATHLETIC vs NOT ATHELTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ATHLETIC" "NOT ATHELTIC" 1 NIL)
   :POLE1
   "ATHLETIC"
   :POLE2
   "NOT ATHELTIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-M-FRIEND NIL)
     (POLE1 NIL CHILD-FRIEND NIL)
     (POLE2 NIL WORST-BOSS NIL)))))
 (ESPOSECHRISTIAN
  ("ESPOSECHRISTIAN"
   "ESPOSE CHRISTIAN vs NOT ESPOUSE CHRISTIAN"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ESPOSE CHRISTIAN" "NOT ESPOUSE CHRISTIAN" 1 NIL)
   :POLE1
   "ESPOSE CHRISTIAN"
   :POLE2
   "NOT ESPOUSE CHRISTIAN"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL FAV-TEACHER NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (CRITICAL
  ("CRITICAL"
   "CRITICAL vs NOT CRITICAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CRITICAL" "NOT CRITICAL" 2 NIL)
   :POLE1
   "CRITICAL"
   :POLE2
   "NOT CRITICAL"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL WORST-BOSS NIL)
     (POLE1 NIL DIS-TEACHER NIL)
     (POLE2 NIL BEST-M-FRIEND NIL)))))
 (SEXDEVIANCE
  ("SEXDEVIANCE"
   "SEX  DEVIANCE vs NOT SEX DEVIANCE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SEX  DEVIANCE" "NOT SEX DEVIANCE" 1 NIL)
   :POLE1
   "SEX  DEVIANCE"
   :POLE2
   "NOT SEX DEVIANCE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-DISLIKE NIL)
     (POLE1 NIL WORK-PER-DISLIKE NIL)
     (POLE2 NIL BEST-F-FRIEND NIL)))))
 (GLOBALPERSPECTIVE
  ("GLOBALPERSPECTIVE"
   "GLOBAL PERSPECTIVE vs NARROW PERSPECTIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GLOBAL PERSPECTIVE" "NARROW PERSPECTIVE" 1 NIL)
   :POLE1
   "GLOBAL PERSPECTIVE"
   :POLE2
   "NARROW PERSPECTIVE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL F-DISLIKE NIL)))))
 (FUNCOMPANION
  ("FUNCOMPANION"
   "FUN COMPANION vs NOT FUN COMPAN"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("FUN COMPANION" "NOT FUN COMPAN" 1 NIL)
   :POLE1
   "FUN COMPANION"
   :POLE2
   "NOT FUN COMPAN"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL PER-ROMANCE NIL)
     (POLE2 NIL F-ADMIRE NIL)))))
 (SELF-DISCLOSE
  ("SELF-DISCLOSE"
   "SELF-DISCLOSE vs NOT SELF-DISCLOSE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SELF-DISCLOSE" "NOT SELF-DISCLOSE" 1 NIL)
   :POLE1
   "SELF-DISCLOSE"
   :POLE2
   "NOT SELF-DISCLOSE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL PER-MOSTFUN NIL)
     (POLE2 NIL WORST-BOSS NIL)))))
 (MISSIONSPREADPSYCH
  ("MISSIONSPREADPSYCH"
   "MISSION TO SPREAD PSYCH KNOWLEDGE vs NOT PSY MISSION"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("MISSION TO SPREAD PSYCH KNOWLEDGE" "NOT PSY MISSION" 1 NIL)
   :POLE1
   "MISSION TO SPREAD PSYCH KNOWLEDGE"
   :POLE2
   "NOT PSY MISSION"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL ROLE-MODEL NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL BEST-F-FRIEND NIL)))))
 (CRUEL
  ("CRUEL"
   "CRUEL vs NOT CRUEL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CRUEL" "NOT CRUEL" 2 NIL)
   :POLE1
   "CRUEL"
   :POLE2
   "NOT CRUEL"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL CHILD-DISLIKE NIL)
     (POLE1 NIL WORK-PER-DISLIKE NIL)
     (POLE2 NIL BEST-F-FRIEND NIL)))))
 (COURTEOUS
  ("COURTEOUS"
   "COURTEOUS vs NOT COURTEOUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("COURTEOUS" "NOT COURTEOUS" 1 NIL)
   :POLE1
   "COURTEOUS"
   :POLE2
   "NOT COURTEOUS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL FAV-TEACHER NIL)
     (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (DEEPUNDERSTANDPEOP
  ("DEEPUNDERSTANDPEOP"
   "DEEP UNDERSTAND PEOPLE vs NOT DEEP UNDERSTAND PEOPLE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DEEP UNDERSTAND PEOPLE" "NOT DEEP UNDERSTAND PEOPLE" 1 NIL)
   :POLE1
   "DEEP UNDERSTAND PEOPLE"
   :POLE2
   "NOT DEEP UNDERSTAND PEOPLE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BEST-F-FRIEND NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL DIS-TEACHER NIL)))))
 (DEMOCRATICLEADER
  ("DEMOCRATICLEADER"
   "DEMOCRATIC LEADER vs AUTOCRATIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DEMOCRATIC LEADER" "AUTOCRATIC" 1 NIL)
   :POLE1
   "DEMOCRATIC LEADER"
   :POLE2
   "AUTOCRATIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL F-ADMIRE NIL)
     (POLE2 NIL M-DISLIKE NIL)))))
 (PSYCHOLOGIST
  ("PSYCHOLOGIST"
   "PSYCHOLOGIST vs NOT PSYCH"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PSYCHOLOGIST" "NOT PSYCH" 1 NIL)
   :POLE1
   "PSYCHOLOGIST"
   :POLE2
   "NOT PSYCH"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-DISLIKE NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL F-ADMIRE NIL)))))
 (METICULOUS
  ("METICULOUS"
   "METICULOUS vs NOT METICULOUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("METICULOUS" "NOT METICULOUS" 1 NIL)
   :POLE1
   "METICULOUS"
   :POLE2
   "NOT METICULOUS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-DISLIKE NIL)
     (POLE1 NIL FAV-SPIRITUAL NIL)
     (POLE2 NIL PER-MOSTFUN NIL)))))
 (COGNITIVEPSYCHS
  ("COGNITIVEPSYCHS"
   "COGNITIVE  PSYCHS vs NOT COG PSY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("COGNITIVE  PSYCHS" "NOT COG PSY" 1 NIL)
   :POLE1
   "COGNITIVE  PSYCHS"
   :POLE2
   "NOT COG PSY"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-DISLIKE NIL)
     (POLE1 NIL ROLE-MODEL NIL)
     (POLE2 NIL FAV-M-STAR NIL)))))
 (EMOTIONAL
  ("EMOTIONAL"
   "EMOTIONAL vs NOT EMOTIONAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("EMOTIONAL" "NOT EMOTIONAL" 2 NIL)
   :POLE1
   "EMOTIONAL"
   :POLE2
   "NOT EMOTIONAL"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL M-DISLIKE NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (CHARMING
  ("CHARMING"
   "CHARMING vs NOT CHARMING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CHARMING" "NOT CHARMING" 1 NIL)
   :POLE1
   "CHARMING"
   :POLE2
   "NOT CHARMING"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-BOSS NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL M-DISLIKE NIL)))))
 (VALUEGROUPHAPPINES
  ("VALUEGROUPHAPPINES"
   "HI VALUE GROUP HAPPINESS vs LO VAL GROUP HAPPY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HI VALUE GROUP HAPPINESS" "LO VAL GROUP HAPPY" 1 NIL)
   :POLE1
   "HI VALUE GROUP HAPPINESS"
   :POLE2
   "LO VAL GROUP HAPPY"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL F-ADMIRE NIL)
     (POLE2 NIL F-DISLIKE NIL)))))
 (LOCALLEADER
  ("LOCALLEADER"
   "LOCAL LEADER vs GLOBAL LEADER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LOCAL LEADER" "GLOBAL LEADER" 2 NIL)
   :POLE1
   "LOCAL LEADER"
   :POLE2
   "GLOBAL LEADER"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL F-DISLIKE NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL F-ADMIRE NIL)))))
 (HIGHLYEDUCATED
  ("HIGHLYEDUCATED"
   "HIGHLY EDUCATED vs LESS EDUCATION"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HIGHLY EDUCATED" "LESS EDUCATION" 1 NIL)
   :POLE1
   "HIGHLY EDUCATED"
   :POLE2
   "LESS EDUCATION"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-DISLIKE NIL)
     (POLE1 NIL FAV-SPIRITUAL NIL)
     (POLE2 NIL PER-MOSTFUN NIL)))))
 (ENLIGHTENWORLD
  ("ENLIGHTENWORLD"
   "ENLIGHTEN WORLD vs NOT ENLIGHTEN WORLD"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ENLIGHTEN WORLD" "NOT ENLIGHTEN WORLD" 1 NIL)
   :POLE1
   "ENLIGHTEN WORLD"
   :POLE2
   "NOT ENLIGHTEN WORLD"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL ROLE-MODEL NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL F-DISLIKE NIL)))))
 (PETTY
  ("PETTY"
   "PETTY vs BIG ISSUE FOCUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PETTY" "BIG ISSUE FOCUS" 2 NIL)
   :POLE1
   "PETTY"
   :POLE2
   "BIG ISSUE FOCUS"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL F-DISLIKE NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (ENCOURAGING
  ("ENCOURAGING"
   "ENCOURAGING vs DISCOURAGING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ENCOURAGING" "DISCOURAGING" 1 NIL)
   :POLE1
   "ENCOURAGING"
   :POLE2
   "DISCOURAGING"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-BOSS NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL F-DISLIKE NIL)))))
 (HUMOROUS
  ("HUMOROUS"
   "HUMOROUS vs NOT HUMOROUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HUMOROUS" "NOT HUMOROUS" 1 NIL)
   :POLE1
   "HUMOROUS"
   :POLE2
   "NOT HUMOROUS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL PER-MOSTFUN NIL)
     (POLE2 NIL F-ADMIRE NIL)))))
 (GREATLEADER
  ("GREATLEADER"
   "GREAT LEADER vs NOT GREAT LEADER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GREAT LEADER" "NOT GREAT LEADER" 1 NIL)
   :POLE1
   "GREAT LEADER"
   :POLE2
   "NOT GREAT LEADER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL FAV-BOSS NIL)
     (POLE2 NIL PER-MOSTFUN NIL)))))
 (CONFIDENT-SELF-EST
  ("CONFIDENT-SELF-EST"
   "CONFIDENT-SELF-ESTEEM vs NOT CONFIDENT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CONFIDENT-SELF-ESTEEM" "NOT CONFIDENT" 1 NIL)
   :POLE1
   "CONFIDENT-SELF-ESTEEM"
   :POLE2
   "NOT CONFIDENT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL ROLE-MODEL NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (INTERPERSONALSKILL
  ("INTERPERSONALSKILL"
   "INTERPERSONAL SKILLS vs NOT INTERP SKILLS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INTERPERSONAL SKILLS" "NOT INTERP SKILLS" 1 NIL)
   :POLE1
   "INTERPERSONAL SKILLS"
   :POLE2
   "NOT INTERP SKILLS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (INTIMATELYASSERTIV
  ("INTIMATELYASSERTIV"
   "INTIMATELY ASSERTIVE LEADER vs NOT INTIMATE-ASSERT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INTIMATELY ASSERTIVE LEADER" "NOT INTIMATE-ASSERT" 1 NIL)
   :POLE1
   "INTIMATELY ASSERTIVE LEADER"
   :POLE2
   "NOT INTIMATE-ASSERT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL M-ADMIRE NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (GREATSPEAKER
  ("GREATSPEAKER"
   "GREAT SPEAKER vs NOT GREAT SPEAKER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GREAT SPEAKER" "NOT GREAT SPEAKER" 1 NIL)
   :POLE1
   "GREAT SPEAKER"
   :POLE2
   "NOT GREAT SPEAKER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-POLITICO NIL)
     (POLE1 NIL FAV-SPIRITUAL NIL)
     (POLE2 NIL M-ADMIRE NIL)))))
 (AUTONOMOUS
  ("AUTONOMOUS"
   "AUTONOMOUS vs NOT AUTONOMOUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("AUTONOMOUS" "NOT AUTONOMOUS" 1 NIL)
   :POLE1
   "AUTONOMOUS"
   :POLE2
   "NOT AUTONOMOUS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-ADMIRE NIL)
     (POLE1 NIL PER-ROMANCE NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (HIGHINTELLIGENCE
  ("HIGHINTELLIGENCE"
   "HIGH INTELLIGENCE vs NOT INTELLIGENT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HIGH INTELLIGENCE" "NOT INTELLIGENT" 1 NIL)
   :POLE1
   "HIGH INTELLIGENCE"
   :POLE2
   "NOT INTELLIGENT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-ADMIRE NIL)
     (POLE1 NIL ROLE-MODEL NIL)
     (POLE2 NIL DIS-TEACHER NIL)))))
 (GOODNEGOTIATOR
  ("GOODNEGOTIATOR"
   "GOOD NEGOTIATOR vs NOT GOOD NEGOTIATOR"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GOOD NEGOTIATOR" "NOT GOOD NEGOTIATOR" 1 NIL)
   :POLE1
   "GOOD NEGOTIATOR"
   :POLE2
   "NOT GOOD NEGOTIATOR"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-ADMIRE NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (PROGRESSIVE
  ("PROGRESSIVE"
   "PROGRESSIVE vs NOT PROGRESSIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PROGRESSIVE" "NOT PROGRESSIVE" 1 NIL)
   :POLE1
   "PROGRESSIVE"
   :POLE2
   "NOT PROGRESSIVE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL F-ADMIRE NIL)
     (POLE1 NIL FAV-BOSS NIL)
     (POLE2 NIL DIS-TEACHER NIL)))))
 (CLOSE ("CLOSE"
         "CLOSE TO ME vs DISTANT"
         CS2-1-1-99
         NIL
         NIL
         :PC
         ("CLOSE TO ME" "DISTANT" 1 NIL)
         :POLE1
         "CLOSE TO ME"
         :POLE2
         "DISTANT"
         :BESTPOLE
         1
         (:BIPATHS
          ((POLE1 NIL PER-MOSTFUN NIL)
           (POLE1 NIL PER-ROMANCE NIL)
           (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (PLAYFUL
  ("PLAYFUL"
   "PLAYFUL vs NOT PLAYFUL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PLAYFUL" "NOT PLAYFUL" 1 NIL)
   :POLE1
   "PLAYFUL"
   :POLE2
   "NOT PLAYFUL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL PER-MOSTFUN NIL)
     (POLE1 NIL CHILD-FRIEND NIL)
     (POLE2 NIL WORK-FRIEND NIL)))))
 (COUNSELORS
  ("COUNSELORS"
   "COUNSELORS vs NOT COUNSELOR"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("COUNSELORS" "NOT COUNSELOR" 1 NIL)
   :POLE1
   "COUNSELORS"
   :POLE2
   "NOT COUNSELOR"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL WORST-BOSS NIL)
     (POLE2 NIL PER-MOSTFUN NIL)))))
 (INDUSTRIOUS
  ("INDUSTRIOUS"
   "INDUSTRIOUS vs LESS INDUSTRIOUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INDUSTRIOUS" "LESS INDUSTRIOUS" 2 NIL)
   :POLE1
   "INDUSTRIOUS"
   :POLE2
   "LESS INDUSTRIOUS"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL PER-MOSTFUN NIL)
     (POLE1 NIL WORST-BOSS NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (SEXY
  ("SEXY"
   "SEXY vs NOT SEXY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SEXY" "NOT SEXY" 1 NIL)
   :POLE1
   "SEXY"
   :POLE2
   "NOT SEXY"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL PER-ROMANCE NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL ROLE-MODEL NIL)))))
 (UNDERSTANDING4
  ("UNDERSTANDING4"
   "UNDERSTANDING vs NOT UNDERSTANDING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("UNDERSTANDING" "NOT UNDERSTANDING" 1 NIL)
   :POLE1
   "UNDERSTANDING"
   :POLE2
   "NOT UNDERSTANDING"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL PER-ROMANCE NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (SOFTSPOKEN
  ("SOFTSPOKEN"
   "SOFT SPOKEN vs NOT SOFT SPOKEN"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SOFT SPOKEN" "NOT SOFT SPOKEN" 1 NIL)
   :POLE1
   "SOFT SPOKEN"
   :POLE2
   "NOT SOFT SPOKEN"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-BOSS NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL PER-ROMANCE NIL)))))
 (TEAMMATE
  ("TEAMMATE"
   "TEAMMATE vs NOT TEAMMATE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("TEAMMATE" "NOT TEAMMATE" 1 NIL)
   :POLE1
   "TEAMMATE"
   :POLE2
   "NOT TEAMMATE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL CHILD-FRIEND NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL ROLE-MODEL NIL)))))
 (BEHAVIORALPSYCH
  ("BEHAVIORALPSYCH"
   "BEHAVIORAL PSYCH vs NOT BEH PSY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("BEHAVIORAL PSYCH" "NOT BEH PSY" 1 NIL)
   :POLE1
   "BEHAVIORAL PSYCH"
   :POLE2
   "NOT BEH PSY"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL ROLE-MODEL NIL)
     (POLE1 NIL WORK-FRIEND NIL)
     (POLE2 NIL FAV-BOSS NIL)))))
 (OPTIMISTIC
  ("OPTIMISTIC"
   "OPTIMISTIC vs NOT OPTIMISTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("OPTIMISTIC" "NOT OPTIMISTIC" 1 NIL)
   :POLE1
   "OPTIMISTIC"
   :POLE2
   "NOT OPTIMISTIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL ROLE-MODEL NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL WORST-BOSS NIL)))))
 (CHILDHOODFRIEND
  ("CHILDHOODFRIEND"
   "CHILDHOOD FRIEND vs NOT CHILDHOOD FRIEND"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CHILDHOOD FRIEND" "NOT CHILDHOOD FRIEND" 1 NIL)
   :POLE1
   "CHILDHOOD FRIEND"
   :POLE2
   "NOT CHILDHOOD FRIEND"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL CHILD-FRIEND NIL)
     (POLE1 NIL CHILD-DISLIKE NIL)
     (POLE2 NIL FAV-POLITICO NIL)))))
 (DEBONAIRE
  ("DEBONAIRE"
   "DEBONAIRE vs NOT DEBONAIRE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DEBONAIRE" "NOT DEBONAIRE" 1 NIL)
   :POLE1
   "DEBONAIRE"
   :POLE2
   "NOT DEBONAIRE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-BOSS NIL)
     (POLE1 NIL FAV-M-STAR NIL)
     (POLE2 NIL CHILD-FRIEND NIL)))))
 (HIGHSTANDARDS
  ("HIGHSTANDARDS"
   "HIGH STANDARDS vs LOW STANDARDS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HIGH STANDARDS" "LOW STANDARDS" 1 NIL)
   :POLE1
   "HIGH STANDARDS"
   :POLE2
   "LOW STANDARDS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL WORK-PER-DISLIKE NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (TEACHER1
  ("TEACHER1"
   "TEACHER vs NOT TEACHER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("TEACHER" "NOT TEACHER" 1 NIL)
   :POLE1
   "TEACHER"
   :POLE2
   "NOT TEACHER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-BOSS NIL)
     (POLE1 NIL DIS-TEACHER NIL)
     (POLE2 NIL CHILD-DISLIKE NIL)))))
 (LIBERALCHRISTIAN
  ("LIBERALCHRISTIAN"
   "LIBERAL CHRISTIAN vs NOT LIBERAL CHRIST"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LIBERAL CHRISTIAN" "NOT LIBERAL CHRIST" 1 NIL)
   :POLE1
   "LIBERAL CHRISTIAN"
   :POLE2
   "NOT LIBERAL CHRIST"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL FAV-TEACHER NIL)
     (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (EMPATHETICLISTENER
  ("EMPATHETICLISTENER"
   "EMPATHETIC LISTENER vs NOT EMPATHETIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("EMPATHETIC LISTENER" "NOT EMPATHETIC" 1 NIL)
   :POLE1
   "EMPATHETIC LISTENER"
   :POLE2
   "NOT EMPATHETIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORK-FRIEND NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL DIS-TEACHER NIL)))))
 (OVERCOMEDIFFICULTI
  ("OVERCOMEDIFFICULTI"
   "OVERCOME DIFFICULTIES vs LESS OVERCOME"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("OVERCOME DIFFICULTIES" "LESS OVERCOME" 1 NIL)
   :POLE1
   "OVERCOME DIFFICULTIES"
   :POLE2
   "LESS OVERCOME"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FAV-POLITICO NIL)
     (POLE1 NIL FAV-SPIRITUAL NIL)
     (POLE2 NIL WORK-PER-DISLIKE NIL)))))
 (FIGHTILLNESS
  ("FIGHTILLNESS"
   "FIGHT  ILLNESS vs NOT FIGHT ILLNESS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("FIGHT  ILLNESS" "NOT FIGHT ILLNESS" 1 NIL)
   :POLE1
   "FIGHT  ILLNESS"
   :POLE2
   "NOT FIGHT ILLNESS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL WORST-BOSS NIL)
     (POLE1 NIL FAV-POLITICO NIL)
     (POLE2 NIL FAV-M-STAR NIL)))))
 (PUBLICSERVANT
  ("PUBLICSERVANT"
   "PUBLIC SERVANT vs NOT PUBLIC SERVANT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PUBLIC SERVANT" "NOT PUBLIC SERVANT" 0 NIL)
   :POLE1
   "PUBLIC SERVANT"
   :POLE2
   "NOT PUBLIC SERVANT"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL POLICEMAN NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (SECULAR
  ("SECULAR"
   "SECULAR vs RELIGIOUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SECULAR" "RELIGIOUS" 0 NIL)
   :POLE1
   "SECULAR"
   :POLE2
   "RELIGIOUS"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL POLICEMAN NIL)
     (POLE2 NIL MUSLIMS NIL)))))
 (SEEKATTENTION
  ("SEEKATTENTION"
   "SEEK ATTENTION vs LESS SEEK ATTENTION"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SEEK ATTENTION" "LESS SEEK ATTENTION" 0 NIL)
   :POLE1
   "SEEK ATTENTION"
   :POLE2
   "LESS SEEK ATTENTION"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL MOVIE-STAR NIL)
     (POLE2 NIL TEACHER NIL)))))
 (HELPER
  ("HELPER"
   "HELPER vs NOT HELPER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HELPER" "NOT HELPER" 1 NIL)
   :POLE1
   "HELPER"
   :POLE2
   "NOT HELPER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL) (POLE1 NIL DOCTOR NIL) (POLE2 NIL DANCER NIL)))))
 (SPREADKNOWLEDGE
  ("SPREADKNOWLEDGE"
   "SPREAD KNOWLEDGE vs NOT SPREAD KNOW"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SPREAD KNOWLEDGE" "NOT SPREAD KNOW" 1 NIL)
   :POLE1
   "SPREAD KNOWLEDGE"
   :POLE2
   "NOT SPREAD KNOW"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL SCIENTIST NIL)
     (POLE2 NIL LAWYER NIL)))))
 (LAWFUL
  ("LAWFUL"
   "LAWFUL vs LESS LAWFUL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LAWFUL" "LESS LAWFUL" 1 NIL)
   :POLE1
   "LAWFUL"
   :POLE2
   "LESS LAWFUL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL) (POLE1 NIL LAWYER NIL) (POLE2 NIL BLACKS NIL)))))
 (MANAGER0
  ("MANAGER0"
   "MANAGER vs NOT MANAGER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("MANAGER" "NOT MANAGER" 1 NIL)
   :POLE1
   "MANAGER"
   :POLE2
   "NOT MANAGER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL BUSINESS-OWNER NIL)
     (POLE2 NIL ATHEISTS NIL)))))
 (PRAGMATIC
  ("PRAGMATIC"
   "PRAGMATIC vs NOT PRAGMATIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PRAGMATIC" "NOT PRAGMATIC" 1 NIL)
   :POLE1
   "PRAGMATIC"
   :POLE2
   "NOT PRAGMATIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL MANAGER NIL)
     (POLE2 NIL MUSLIMS NIL)))))
 (GROUPKNOWLEDGEWORK
  ("GROUPKNOWLEDGEWORK"
   "GROUP KNOWLEDGE WORKER vs NOT GROUP KNOWL WORK"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GROUP KNOWLEDGE WORKER" "NOT GROUP KNOWL WORK" 1 NIL)
   :POLE1
   "GROUP KNOWLEDGE WORKER"
   :POLE2
   "NOT GROUP KNOWL WORK"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL SCIENTIST NIL)
     (POLE2 NIL JEWS NIL)))))
 (VERBALSKILLS
  ("VERBALSKILLS"
   "HI VERBAL SKILLS vs LO VERBAL SKILLS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HI VERBAL SKILLS" "LO VERBAL SKILLS" 1 NIL)
   :POLE1
   "HI VERBAL SKILLS"
   :POLE2
   "LO VERBAL SKILLS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL) (POLE1 NIL JEWS NIL) (POLE2 NIL FARMER NIL)))))
 (LESSCIVILIZED
  ("LESSCIVILIZED"
   "LESS CIVILIZED vs CIVILIZED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LESS CIVILIZED" "CIVILIZED" 2 NIL)
   :POLE1
   "LESS CIVILIZED"
   :POLE2
   "CIVILIZED"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL DRUG-DEALER NIL)
     (POLE1 NIL MUSLIMS NIL)
     (POLE2 NIL TEACHER NIL)))))
 (REPRESENTGROUP
  ("REPRESENTGROUP"
   "REPRESENT GROUP vs NOT REPRESENT GROUP"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("REPRESENT GROUP" "NOT REPRESENT GROUP" 1 NIL)
   :POLE1
   "REPRESENT GROUP"
   :POLE2
   "NOT REPRESENT GROUP"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL POLITICIAN NIL)
     (POLE2 NIL ATHEISTS NIL)))))
 (PERFORMER
  ("PERFORMER"
   "PERFORMER vs NOT PERFORMER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PERFORMER" "NOT PERFORMER" 0 NIL)
   :POLE1
   "PERFORMER"
   :POLE2
   "NOT PERFORMER"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL) (POLE1 NIL DANCER NIL) (POLE2 NIL BLACKS NIL)))))
 (SHOWBUSINESS
  ("SHOWBUSINESS"
   "SHOW BUSINESS vs NOT SHOW BUSINESS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SHOW BUSINESS" "NOT SHOW BUSINESS" 0 NIL)
   :POLE1
   "SHOW BUSINESS"
   :POLE2
   "NOT SHOW BUSINESS"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL COMEDIAN NIL)
     (POLE1 NIL MOVIE-STAR NIL)
     (POLE2 NIL TEACHER NIL)))))
 (SOLVEPROBLEMS
  ("SOLVEPROBLEMS"
   "SOLVE PROBLEMS vs LESS SOLVE PROBLEMS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SOLVE PROBLEMS" "LESS SOLVE PROBLEMS" 1 NIL)
   :POLE1
   "SOLVE PROBLEMS"
   :POLE2
   "LESS SOLVE PROBLEMS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL ENGINEER NIL)
     (POLE2 NIL MUSLIMS NIL)))))
 (STARPERFORMER
  ("STARPERFORMER"
   "A STAR PERFORMER vs NOT STAR PERFORMER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("A STAR PERFORMER" "NOT STAR PERFORMER" 1 NIL)
   :POLE1
   "A STAR PERFORMER"
   :POLE2
   "NOT STAR PERFORMER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL MOVIE-STAR NIL)
     (POLE1 NIL ROCK-STAR NIL)
     (POLE2 NIL TEACHER NIL)))))
 (LESSWEALTH
  ("LESSWEALTH"
   "LESS WEALTH vs WEALTHY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LESS WEALTH" "WEALTHY" 2 NIL)
   :POLE1
   "LESS WEALTH"
   :POLE2
   "WEALTHY"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL HISPANICS NIL)
     (POLE2 NIL ROCK-STAR NIL)))))
 (DEPENDGOV
  ("DEPENDGOV"
   "DEPEND ON GOV vs LESS DEPEND ON GOV"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DEPEND ON GOV" "LESS DEPEND ON GOV" 1 NIL)
   :POLE1
   "DEPEND ON GOV"
   :POLE2
   "LESS DEPEND ON GOV"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL TEACHER NIL)
     (POLE1 NIL BLACKS NIL)
     (POLE2 NIL CATHOLICS NIL)))))
 (IMMIGRANTS
  ("IMMIGRANTS"
   "IMMIGRANTS vs LESS IMMIGRANTS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("IMMIGRANTS" "LESS IMMIGRANTS" 0 NIL)
   :POLE1
   "IMMIGRANTS"
   :POLE2
   "LESS IMMIGRANTS"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL MUSLIMS NIL)
     (POLE1 NIL HISPANICS NIL)
     (POLE2 NIL TEACHER NIL)))))
 (PROFIT-ORIENTED
  ("PROFIT-ORIENTED"
   "PROFIT-ORIENTED vs LESS PROFIT-ORIENTED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PROFIT-ORIENTED" "LESS PROFIT-ORIENTED" 2 NIL)
   :POLE1
   "PROFIT-ORIENTED"
   :POLE2
   "LESS PROFIT-ORIENTED"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL BUSINESS-OWNER NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (OCCUPATION
  ("OCCUPATION"
   "OCCUPATION vs NOT OCCUPATION"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("OCCUPATION" "NOT OCCUPATION" 0 NIL)
   :POLE1
   "OCCUPATION"
   :POLE2
   "NOT OCCUPATION"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL SALESPERSON NIL)
     (POLE2 NIL ANGLOS NIL)))))
 (PHYSICALWELLBEING
  ("PHYSICALWELLBEING"
   "PHYSICAL WELLBEING vs SPIRITUAL WELLBEING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PHYSICAL WELLBEING" "SPIRITUAL WELLBEING" 0 NIL)
   :POLE1
   "PHYSICAL WELLBEING"
   :POLE2
   "SPIRITUAL WELLBEING"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL DOCTOR NIL)
     (POLE2 NIL PROTESTANTS NIL)))))
 (LEGALEXPERT
  ("LEGALEXPERT"
   "LEGAL EXPERT vs NOT LEGAL EXPERT"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LEGAL EXPERT" "NOT LEGAL EXPERT" 1 NIL)
   :POLE1
   "LEGAL EXPERT"
   :POLE2
   "NOT LEGAL EXPERT"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL LAWYER NIL)
     (POLE2 NIL MOVIE-STAR NIL)))))
 (SELF-DISCIPLINE
  ("SELF-DISCIPLINE"
   "SELF-DISCIPLINE vs LESS SELF-DISCIPLINE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SELF-DISCIPLINE" "LESS SELF-DISCIPLINE" 1 NIL)
   :POLE1
   "SELF-DISCIPLINE"
   :POLE2
   "LESS SELF-DISCIPLINE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL BUSINESS-OWNER NIL)
     (POLE2 NIL COMEDIAN NIL)))))
 (ENFORCERULES
  ("ENFORCERULES"
   "ENFORCE RULES vs NOT ENFORCE RULES"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("ENFORCE RULES" "NOT ENFORCE RULES" 0 NIL)
   :POLE1
   "ENFORCE RULES"
   :POLE2
   "NOT ENFORCE RULES"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL MANAGER NIL)
     (POLE1 NIL DANCER NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (CREATENEWRULES
  ("CREATENEWRULES"
   "CREATE NEW RULES vs NOT CREATE RULES"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CREATE NEW RULES" "NOT CREATE RULES" 1 NIL)
   :POLE1
   "CREATE NEW RULES"
   :POLE2
   "NOT CREATE RULES"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL SCIENTIST NIL)
     (POLE1 NIL POLITICIAN NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (SOCIALCONSTRAINTS
  ("SOCIALCONSTRAINTS"
   "SOCIAL CONSTRAINTS vs FREE FROM SOCIAL CONTRANTS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SOCIAL CONSTRAINTS" "FREE FROM SOCIAL CONTRANTS" 2 NIL)
   :POLE1
   "SOCIAL CONSTRAINTS"
   :POLE2
   "FREE FROM SOCIAL CONTRANTS"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL POLITICIAN NIL)
     (POLE2 NIL FARMER NIL)))))
 (RESPECTED
  ("RESPECTED"
   "RESPECTED vs NOT RESPECTED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("RESPECTED" "NOT RESPECTED" 1 NIL)
   :POLE1
   "RESPECTED"
   :POLE2
   "NOT RESPECTED"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL DANCER NIL)
     (POLE2 NIL DRUG-DEALER NIL)))))
 (SEEKEXTERNALAPPROV
  ("SEEKEXTERNALAPPROV"
   "SEEK EXTERNAL APPROVAL vs NOT SEEK EXT APPROVAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SEEK EXTERNAL APPROVAL" "NOT SEEK EXT APPROVAL" 2 NIL)
   :POLE1
   "SEEK EXTERNAL APPROVAL"
   :POLE2
   "NOT SEEK EXT APPROVAL"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL POLITICIAN NIL)
     (POLE1 NIL COMEDIAN NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (CREATIVE
  ("CREATIVE"
   "CREATIVE vs NOT CREATIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CREATIVE" "NOT CREATIVE" 1 NIL)
   :POLE1
   "CREATIVE"
   :POLE2
   "NOT CREATIVE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL DANCER NIL)
     (POLE1 NIL MOVIE-STAR NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (RITUALISTIC
  ("RITUALISTIC"
   "RITUALISTIC vs NOT RITUALISTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("RITUALISTIC" "NOT RITUALISTIC" 1 NIL)
   :POLE1
   "RITUALISTIC"
   :POLE2
   "NOT RITUALISTIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL PROTESTANTS NIL)
     (POLE2 NIL ARTIST NIL)))))
 (LESSMORALISTIC
  ("LESSMORALISTIC"
   "LESS MORALISTIC vs MORALISTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("LESS MORALISTIC" "MORALISTIC" 0 NIL)
   :POLE1
   "LESS MORALISTIC"
   :POLE2
   "MORALISTIC"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL COMEDIAN NIL)
     (POLE1 NIL ANGLOS NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (PROFESSIONAL
  ("PROFESSIONAL"
   "PROFESSIONAL vs NOT PROFESSIONAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PROFESSIONAL" "NOT PROFESSIONAL" 1 NIL)
   :POLE1
   "PROFESSIONAL"
   :POLE2
   "NOT PROFESSIONAL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL CHURCH-MINISTER NIL)
     (POLE2 NIL HOUSE-CLEANER NIL)))))
 (DRAMATIC
  ("DRAMATIC"
   "DRAMATIC vs LESS DRAMATIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("DRAMATIC" "LESS DRAMATIC" 0 NIL)
   :POLE1
   "DRAMATIC"
   :POLE2
   "LESS DRAMATIC"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL MOVIE-STAR NIL)
     (POLE1 NIL HISPANICS NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (EUROCENTRICVALUES
  ("EUROCENTRICVALUES"
   "EUROCENTRIC VALUES vs NOT EUROENTRIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("EUROCENTRIC VALUES" "NOT EUROENTRIC" 1 NIL)
   :POLE1
   "EUROCENTRIC VALUES"
   :POLE2
   "NOT EUROENTRIC"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL CHURCH-MINISTER NIL)
     (POLE1 NIL ANGLOS NIL)
     (POLE2 NIL POLICEMAN NIL)))))
 (INDIVIDUALISTIC
  ("INDIVIDUALISTIC"
   "INDIVIDUALISTIC vs GROUP-CONTROLLED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INDIVIDUALISTIC" "GROUP-CONTROLLED" 2 NIL)
   :POLE1
   "INDIVIDUALISTIC"
   :POLE2
   "GROUP-CONTROLLED"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL ASIANS NIL)
     (POLE2 NIL PROTESTANTS NIL)))))
 (CATHOLIC
  ("CATHOLIC"
   "CATHOLIC vs NOT CATHOLIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("CATHOLIC" "NOT CATHOLIC" 0 NIL)
   :POLE1
   "CATHOLIC"
   :POLE2
   "NOT CATHOLIC"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL POLICEMAN NIL)
     (POLE1 NIL HISPANICS NIL)
     (POLE2 NIL ATHEISTS NIL)))))
 (PEOPLE-JOB
  ("PEOPLE-JOB"
   "PEOPLE-JOB vs OBJECT-JOB"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PEOPLE-JOB" "OBJECT-JOB" 0 NIL)
   :POLE1
   "PEOPLE-JOB"
   :POLE2
   "OBJECT-JOB"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL DOCTOR NIL)
     (POLE2 NIL HOUSE-CLEANER NIL)))))
 (GREEDY
  ("GREEDY"
   "GREEDY vs NOT GREEDY"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("GREEDY" "NOT GREEDY" 2 NIL)
   :POLE1
   "GREEDY"
   :POLE2
   "NOT GREEDY"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL LAWYER NIL)
     (POLE2 NIL DANCER NIL)))))
 (OWNER
  ("OWNER"
   "OWNER vs NOT OWNER"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("OWNER" "NOT OWNER" 1 NIL)
   :POLE1
   "OWNER"
   :POLE2
   "NOT OWNER"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL BUSINESS-OWNER NIL)
     (POLE1 NIL FARMER NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (PERFORMANCE-ORIENT
  ("PERFORMANCE-ORIENT"
   "PERFORMANCE-ORIENTED vs NOT PERFORM-ORIENTED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PERFORMANCE-ORIENTED" "NOT PERFORM-ORIENTED" 1 NIL)
   :POLE1
   "PERFORMANCE-ORIENTED"
   :POLE2
   "NOT PERFORM-ORIENTED"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL BUSINESS-OWNER NIL)
     (POLE2 NIL ASIANS NIL)))))
 (HIGHSTATUS
  ("HIGHSTATUS"
   "HIGH STATUS vs LOW STATUS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("HIGH STATUS" "LOW STATUS" 1 NIL)
   :POLE1
   "HIGH STATUS"
   :POLE2
   "LOW STATUS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL MANAGER NIL)
     (POLE2 NIL HISPANICS NIL)))))
 (RATIONAL ("RATIONAL"
            "RATIONAL vs NOT RATIONAL"
            CS2-1-1-99
            NIL
            NIL
            :PC
            ("RATIONAL" "NOT RATIONAL" 1 NIL)
            :POLE1
            "RATIONAL"
            :POLE2
            "NOT RATIONAL"
            :BESTPOLE
            1
            (:BIPATHS
             ((POLE1 NIL SCIENTIST NIL)
              (POLE1 NIL ANGLOS NIL)
              (POLE2 NIL SALESPERSON NIL)))))
 (PRACTICAL
  ("PRACTICAL"
   "PRACTICAL vs NOT PRACTICAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PRACTICAL" "NOT PRACTICAL" 1 NIL)
   :POLE1
   "PRACTICAL"
   :POLE2
   "NOT PRACTICAL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL FARMER NIL)
     (POLE1 NIL ANGLOS NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (PERSUASIVE
  ("PERSUASIVE"
   "PERSUASIVE  vs LESS PERSUASIVE"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("PERSUASIVE " "LESS PERSUASIVE" 1 NIL)
   :POLE1
   "PERSUASIVE "
   :POLE2
   "LESS PERSUASIVE"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL DRUG-DEALER NIL)
     (POLE2 NIL HISPANICS NIL)))))
 (INFLUENCIAL
  ("INFLUENCIAL"
   "INFLUENCIAL vs NOT INFLUENCIAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("INFLUENCIAL" "NOT INFLUENCIAL" 1 NIL)
   :POLE1
   "INFLUENCIAL"
   :POLE2
   "NOT INFLUENCIAL"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL POLITICIAN NIL)
     (POLE2 NIL ASIANS NIL)))))
 (MANUALWORK
  ("MANUALWORK"
   "MANUAL WORK vs NOT MANUAL WORK"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("MANUAL WORK" "NOT MANUAL WORK" 0 NIL)
   :POLE1
   "MANUAL WORK"
   :POLE2
   "NOT MANUAL WORK"
   :BESTPOLE
   0
   (:BIPATHS
    ((POLE1 NIL ARTIST NIL)
     (POLE1 NIL HOUSE-CLEANER NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (NOTHISTORY-ORIENTE
  ("NOTHISTORY-ORIENTE"
   "NOT HISTORY-ORIENTED vs HISTORY-ORIENTED"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("NOT HISTORY-ORIENTED" "HISTORY-ORIENTED" 2 NIL)
   :POLE1
   "NOT HISTORY-ORIENTED"
   :POLE2
   "HISTORY-ORIENTED"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL COMEDIAN NIL)
     (POLE2 NIL PROTESTANTS NIL)))))
 (NOTANALYTIC
  ("NOTANALYTIC"
   "NOT ANALYTIC vs ANALYTIC THINKING"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("NOT ANALYTIC" "ANALYTIC THINKING" 2 NIL)
   :POLE1
   "NOT ANALYTIC"
   :POLE2
   "ANALYTIC THINKING"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL HISPANICS NIL)
     (POLE2 NIL ENGINEER NIL)))))
 (NOTLOYAL
  ("NOTLOYAL"
   "NOT LOYAL vs LOYAL"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("NOT LOYAL" "LOYAL" 2 NIL)
   :POLE1
   "NOT LOYAL"
   :POLE2
   "LOYAL"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL MOVIE-STAR NIL)
     (POLE2 NIL JEWS NIL)))))
 (SPIRITUALINTEGRATI
  ("SPIRITUALINTEGRATI"
   "SPIRITUAL INTEGRATION vs NOT SPIRIT INTEGR"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SPIRITUAL INTEGRATION" "NOT SPIRIT INTEGR" 1 NIL)
   :POLE1
   "SPIRITUAL INTEGRATION"
   :POLE2
   "NOT SPIRIT INTEGR"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL CHURCH-MINISTER NIL)
     (POLE1 NIL PROTESTANTS NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (SEEKULTIMATETRUTH
  ("SEEKULTIMATETRUTH"
   "SEEK ULTIMATE TRUTH vs NOT SEEK ULTIMATES"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SEEK ULTIMATE TRUTH" "NOT SEEK ULTIMATES" 1 NIL)
   :POLE1
   "SEEK ULTIMATE TRUTH"
   :POLE2
   "NOT SEEK ULTIMATES"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL PROTESTANTS NIL)
     (POLE1 NIL BUDDHISTS NIL)
     (POLE2 NIL SALESPERSON NIL)))))
 (MATERIALISTIC
  ("MATERIALISTIC"
   "MATERIALISTIC vs NOT MATERIALISTIC"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("MATERIALISTIC" "NOT MATERIALISTIC" 2 NIL)
   :POLE1
   "MATERIALISTIC"
   :POLE2
   "NOT MATERIALISTIC"
   :BESTPOLE
   2
   (:BIPATHS
    ((POLE1 NIL SALESPERSON NIL)
     (POLE1 NIL ANGLOS NIL)
     (POLE2 NIL BUDDHISTS NIL)))))
 (SKILLEDMOVEMENTS
  ("SKILLEDMOVEMENTS"
   "SKILLED MOVEMENTS vs NOT SKILLED MOVEMENTS"
   CS2-1-1-99
   NIL
   NIL
   :PC
   ("SKILLED MOVEMENTS" "NOT SKILLED MOVEMENTS" 1 NIL)
   :POLE1
   "SKILLED MOVEMENTS"
   :POLE2
   "NOT SKILLED MOVEMENTS"
   :BESTPOLE
   1
   (:BIPATHS
    ((POLE1 NIL DOCTOR NIL) (POLE1 NIL DANCER NIL) (POLE2 NIL LAWYER NIL))))))
  )